.segment BANK(BK_MAIN_CODE)
IRQ_GAME_NTSC:
	; Acknowledge irq
	MMC3_IRQ_DISABLE
	MMC3_IRQ_ENABLE


	LDA	IRQ_COUNTER
	BEQ	IRQ_GAME_NTSC_1
	JMP	IRQ_GAME_NTSC_2

IRQ_GAME_NTSC_1:
	; Wait till next scanline 
	DELAY	63
	PPU_DISABLE_BG
	; DELAY	59
	PPU_SCROLL_XY  0, 6, 192

	MMC3_BANK_SELECT  MMC3_CHR_0, #TS_GAME_UI+0
	MMC3_BANK_SELECT  MMC3_CHR_1, #TS_GAME_UI+2

	PPU_ENABLE

	MMC3_IRQ_DISABLE
	MMC3_IRQ_LATCH 41
	MMC3_IRQ_RELOAD
	MMC3_IRQ_ENABLE

	INC	IRQ_COUNTER
	RTS


IRQ_GAME_NTSC_2:
	; Wait till next scanline 
	DELAY	64
	PPU_DISABLE
	BBS	GAME_FLAG, F_TRANSFER_FIELD, :+
	RTS
:
	BIT	PPUSTATUS

	MMC3_BANK_SELECT  MMC3_PRG_0, #BK_PPU_TRANS
	JSR	NMI_TRANSFER_GAME_FIELD_0
	MMC3_BANK_SELECT  MMC3_PRG_0, SAVED_PRG_0

	INC	IRQ_COUNTER
	RTS
