.segment "STACK"
EXP_BUFFER:	.RES 16 ;Explosion Buffer

.segment "ZEROPAGE"
RANDOM:		.RES 1

TCPIECE1:	.RES 1
TCPIECE2:	.RES 1
TCPIECE3:	.RES 1
TCPIECE4:	.RES 1

DOORPIECE1:	.RES 1
DOORPIECE3:	.RES 1
DOORPIECE2:	.RES 1

PROX_DETECT:	.RES 1 ;0=NO 1=YES
