.segment BANK(BK_HELP)

HELP_BG_PALETTE_DATA:
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE

HELP_SPR_PALETTE_DATA:
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE

HELP_SCREEN_DATA:
HELP_NES_SCREEN_DATA:
	.incbin "resources/screen/help_nes.nt"
	.incbin "resources/screen/help_nes.nt_atr"
HELP_SNES_SCREEN_DATA:
	.incbin "resources/screen/help_snes.nt"
	.incbin "resources/screen/help_snes.nt_atr"
