;this file for FamiStudio Sound Engine generated by FamiStudio

; Info: Header size : 33 bytes.
; Info: Instruments size : 531 bytes.
; Info: Tempo envelopes size : 16 bytes.
; Info: Song 'Metallic Bop' size: 2971 bytes.
; Info: Song 'Rushin In' size: 3420 bytes.
; Info: Total assembly file size: 6971 bytes.
; Info: Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Info: Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Info: Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Info: Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Info: Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Info: Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.

@music_data:
	.byte 2
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env_5_4_mid), .hibyte(@tempo_env_5_4_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4
	.byte .lobyte(@tempo_env_4_3_4_3_4_3_3_3_mid), .hibyte(@tempo_env_4_3_4_3_4_3_3_3_mid), 0, 0

@instruments:
	.word @env28,@env0,@env21,@env15
	.word @env9,@env0,@env21,@env15
	.word @env28,@env0,@env21,@env13
	.word @env30,@env8,@env17,@env26
	.word @env5,@env0,@env16,@env15
	.word @env14,@env4,@env1,@env15
	.word @env5,@env0,@env21,@env15
	.word @env18,@env0,@env16,@env15
	.word @env6,@env3,@env16,@env19
	.word @env20,@env31,@env22,@env15
	.word @env25,@env31,@env10,@env15
	.word @env5,@env31,@env10,@env15
	.word @env5,@env0,@env1,@env15
	.word @env12,@env0,@env16,@env15
	.word @env29,@env2,@env17,@env15
	.word @env29,@env24,@env17,@env15

@samples:
	; .byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$36,$0f,$40	;1 (bark)
	; .byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$22,$0f,$40	;2 (sd1)
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c2,$c0,$00,$01
@env2:
	.byte $c7,$bf,$bb,$b8,$b3,$af,$aa,$a6,$a3,$00,$08
@env3:
	.byte $d0,$ae,$bc,$c2,$00,$03
@env4:
	.byte $d8,$dc,$00,$01
@env5:
	.byte $04,$cf,$7f,$00,$01
@env6:
	.byte $00,$cd,$ca,$c8,$c6,$c4,$02,$c3,$02,$c2,$c2,$c1,$c0,$00,$0c
@env7:
	.byte $c0,$c4,$c7,$00,$00
@env8:
	.byte $cd,$c0,$00,$01
@env9:
	.byte $00,$cf,$ce,$cd,$04,$cc,$02,$cb,$02,$ca,$02,$c9,$c9,$c8,$04,$c7,$02,$c6,$c6,$c5,$04,$c4,$02,$c3,$c3,$c2,$c1,$00,$1a
@env10:
	.byte $c0,$c0,$c1,$c1,$c2,$c2,$c1,$c1,$00,$00
@env11:
	.byte $c0,$cc,$cc,$00,$00
@env12:
	.byte $00,$cf,$03,$ce,$04,$cd,$cd,$cc,$02,$cb,$02,$ca,$02,$c9,$02,$c8,$03,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$03,$c0,$00,$1e
@env13:
	.byte $00,$c0,$bf,$00,$02
@env14:
	.byte $00,$cd,$cc,$cb,$cb,$ca,$ca,$c9,$c8,$c7,$04,$c6,$c6,$c5,$c5,$c4,$03,$c3,$02,$c2,$c1,$02,$c0,$00,$16
@env15:
	.byte $00,$c0,$7f,$00,$01
@env16:
	.byte $7f,$00,$00
@env17:
	.byte $c2,$7f,$00,$00
@env18:
	.byte $00,$ce,$cc,$c8,$c7,$c4,$c0,$00,$06
@env19:
	.byte $00,$c8,$c6,$c5,$c2,$be,$ba,$b7,$95,$00,$08
@env20:
	.byte $00,$ce,$ce,$cd,$cd,$cc,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c6,$c6,$c5,$c3,$c0,$00,$12
@env21:
	.byte $c1,$7f,$00,$00
@env22:
	.byte $c0,$c2,$00,$01
@env23:
	.byte $c0,$c0,$cc,$00,$00
@env24:
	.byte $c7,$c1,$bb,$b8,$b3,$af,$aa,$a6,$a3,$00,$08
@env25:
	.byte $00,$cf,$ce,$03,$cd,$04,$cc,$05,$cb,$02,$ca,$02,$c9,$c9,$c8,$c8,$c7,$03,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$00,$18
@env26:
	.byte $00,$c3,$c0,$00,$02
@env27:
	.byte $c0,$c3,$c7,$00,$00
@env28:
	.byte $00,$cf,$cf,$cd,$cd,$cc,$cc,$cb,$ca,$03,$c9,$c9,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$02,$c3,$c3,$c2,$00,$17
@env29:
	.byte $00,$cf,$ce,$ce,$cd,$cd,$cc,$cb,$cb,$ca,$02,$c9,$c9,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$c2,$c0,$00,$15
@env30:
	.byte $00,$cf,$03,$ce,$cd,$cd,$cc,$cc,$cb,$ca,$c9,$c7,$c6,$c6,$c5,$c5,$c4,$00,$10
@env31:
	.byte $cc,$c0,$00,$01
@env32:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01
@env33:
	.byte $00,$c0,$bf,$be,$be,$bf,$c1,$c2,$c2,$c1,$00,$01
@env34:
	.byte $00,$c0,$bc,$ba,$bb,$be,$c2,$c5,$c6,$c4,$00,$01
@env35:
	.byte $00,$c0,$02,$bf,$0a,$c0,$04,$c1,$0a,$c0,$c0,$00,$01
@tempo_env_5_4_mid:
	.byte $03,$06,$04,$05,$80
@tempo_env_4_3_4_3_4_3_3_3_mid:
	.byte $02,$06,$05,$06,$05,$03,$06,$06,$05,$03,$80
@song0ch0:
@song0ref1:
	.byte $79, $63, .lobyte(@env15), .hibyte(@env15), $64, $86
@song0ref7:
	.byte $10, $a1, $1c, $8f, $10, $a1, $10, $8f, $1a, $8f, $1c, $8f, $10, $a1, $1c, $a1, $00, $c5
@song0ref25:
	.byte $10, $a1, $1c, $8f, $10, $a1, $10, $8f, $1a, $8f, $1c, $8f, $0c, $a1, $0e, $a1, $00, $c5, $6b, $10, $a1, $1c, $8f, $10
	.byte $a1, $10, $8f, $1a, $8f, $1c, $8f, $10, $a1, $00, $e9, $18, $8f, $17, $8f, $15, $8f, $17, $8f, $15, $8f, $13, $8f, $15
	.byte $8f, $13, $8f, $12, $8f, $10, $8f, $0e, $a1, $10, $99, $63, .lobyte(@env32), .hibyte(@env32), $87, $62, $61, $14, $10
	.byte $0e, $a1, $6b, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $4f
	.word @song0ref7
@song0ch0loop:
	.byte $66, $6a, .lobyte(@tempo_env_5_4_mid), .hibyte(@tempo_env_5_4_mid)
	.byte $ff, $24
	.word @song0ref1
	.byte $6b, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $1e
	.word @song0ref7
@song0ref118:
	.byte $1f, $8f, $75, $1f, $8f, $79, $1e, $8f, $75, $1e, $8f, $79, $1c, $8f, $75, $1c, $8f, $79, $1a, $8f, $75, $1a, $8f, $6b
	.byte $79, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $4f
	.word @song0ref7
@song0ref150:
	.byte $6b, $78, $63, .lobyte(@env15), .hibyte(@env15), $64
@song0ref156:
	.byte $10, $a1, $1c, $8f, $10, $a1, $10, $8f, $1a, $8f, $1c, $b3, $1c, $a1, $77, $65, .lobyte(@env27), .hibyte(@env27), $80
	.byte $34, $c5, $78, $65, .lobyte(@env0), .hibyte(@env0), $66, $86, $10, $a1, $1c, $8f, $10, $a1, $10, $8f, $1a, $8f, $1c
	.byte $b3, $1a, $a1, $65, .lobyte(@env7), .hibyte(@env7), $80, $32, $c5, $6b, $65, .lobyte(@env0), .hibyte(@env0), $66, $86
	.byte $13, $a1
@song0ref211:
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $1f, $8f, $13, $a1, $13, $8f, $1d, $8f, $1f, $b3, $1f, $a1, $65, .lobyte(@env27)
	.byte .hibyte(@env27), $80, $34, $c5, $65, .lobyte(@env0), .hibyte(@env0), $66, $86, $0e, $a1, $63, .lobyte(@env15), .hibyte(@env15)
	.byte $64, $1a, $8f, $0e, $a1, $0e, $8f, $18, $8f, $1a, $b3, $18, $a1, $65, .lobyte(@env7), .hibyte(@env7), $80, $32, $c5
	.byte $6b, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env0), .hibyte(@env0), $66, $86
	.byte $ff, $22
	.word @song0ref156
	.byte $77
	.byte $ff, $10
	.word @song0ref211
	.byte $79, $63, .lobyte(@env15), .hibyte(@env15), $64, $13, $8f, $15, $a1, $13, $8f, $15, $8f, $17, $b3, $17, $a1, $65, .lobyte(@env7)
	.byte .hibyte(@env7), $80, $32, $a1, $65, .lobyte(@env0), .hibyte(@env0), $66, $86, $18, $a1
	.byte $ff, $20
	.word @song0ref150
@song0ref312:
	.byte $6b, $65, .lobyte(@env0), .hibyte(@env0), $66, $86, $10, $a1, $77, $63, .lobyte(@env15), .hibyte(@env15), $64, $1c
	.byte $8f, $10, $a1, $10, $8f, $1a, $8f, $1c, $b3, $1c, $a1, $65, .lobyte(@env27), .hibyte(@env27), $80, $34, $c5, $65, .lobyte(@env0)
	.byte .hibyte(@env0), $66, $86, $13, $a1, $79, $63, .lobyte(@env15), .hibyte(@env15), $64, $1f, $8f, $13, $a1, $13, $8f, $21
	.byte $8f, $23, $b3, $21, $a1, $65, .lobyte(@env7), .hibyte(@env7), $80, $32, $c5, $6b, $78, $63, .lobyte(@env15), .hibyte(@env15)
	.byte $64, $65, .lobyte(@env0), .hibyte(@env0), $66, $86
	.byte $ff, $20
	.word @song0ref156
	.byte $ff, $20
	.word @song0ref312
	.byte $6b, $65, .lobyte(@env0), .hibyte(@env0), $66, $86, $10, $a1, $77, $63, .lobyte(@env15), .hibyte(@env15), $64, $1c
	.byte $8f, $10, $a1, $10, $8f, $1a, $8f, $1c, $b3, $1c, $e9
	.byte $ff, $10
	.word @song0ref25
	.byte $10, $c5, $6b, $79, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $24
	.word @song0ref7
	.byte $6b, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $1e
	.word @song0ref7
	.byte $ff, $10
	.word @song0ref118
	.byte $6b, $79, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $24
	.word @song0ref7
	.byte $6b, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $1e
	.word @song0ref7
	.byte $ff, $10
	.word @song0ref118
	.byte $6b, $79, $10, $8f, $10, $8f, $1c, $8f, $10, $a1, $10, $8f, $1f, $8f, $1d, $8f, $1c, $a1, $1a, $c5, $62, $61, $1e, $1a
	.byte $15, $a1
@song0ref486:
	.byte $15, $8f, $13, $8f, $12, $8f, $10, $a1, $17, $8f, $15, $8f, $13, $8f, $15, $a1, $17, $a1, $63, .lobyte(@env33), .hibyte(@env33)
	.byte $a3, $63, .lobyte(@env15), .hibyte(@env15), $64, $18, $a1, $6b, $10, $8f
@song0ref517:
	.byte $10, $8f, $1c, $8f, $10, $a1, $10, $8f, $1c, $8f, $0e, $8f, $1a, $a1, $18, $e9, $0c, $8f, $18, $8f, $0e, $8f, $1a, $a1
	.byte $0e, $8f, $10, $8f, $1c, $8f, $11, $8f, $1d, $8f, $13, $8f, $1f, $8f, $15, $8f, $21, $8f, $17, $8f, $23, $8f, $6b, $24
	.byte $87, $69, $02, $88, $61, $f8, $24, $26, $85, $63, .lobyte(@env34), .hibyte(@env34), $91, $63, .lobyte(@env15), .hibyte(@env15)
	.byte $64, $86, $1a, $8f, $24, $87, $69, $02, $88, $61, $f9, $24, $26, $85, $63, .lobyte(@env34), .hibyte(@env34), $91, $63
	.byte .lobyte(@env15), .hibyte(@env15), $64, $86, $1a, $8f, $26, $8f, $24, $8f, $23, $8f, $21, $8f, $1f, $8f, $1d, $8f, $1e
	.byte $87, $69, $02, $88, $61, $f8, $1e, $1f, $8f, $62, $1f, $85, $63, .lobyte(@env34), .hibyte(@env34), $91, $62, $61, $1a
	.byte $1f, $1c, $8f, $63, .lobyte(@env15), .hibyte(@env15), $64, $86, $23, $8f, $21, $8f, $1f, $8f, $21, $8f, $1f, $8f, $1e
	.byte $8f, $1f, $8f, $1e, $8f, $1c, $8f, $74, $1c, $8f, $79, $1a, $8f, $74, $1a, $8f, $79, $1c, $87, $88, $61, $f7, $1c, $1d
	.byte $85, $63, .lobyte(@env34), .hibyte(@env34), $89, $62, $1d, $a9, $6b, $63, .lobyte(@env15), .hibyte(@env15), $64, $86
	.byte $1f, $87, $88, $1f, $97, $78, $63, .lobyte(@env34), .hibyte(@env34), $9b, $77, $99, $79, $63, .lobyte(@env15), .hibyte(@env15)
	.byte $64, $86, $1c, $8f, $1d, $8f, $1f, $8f, $21, $a1, $78, $63, .lobyte(@env34), .hibyte(@env34), $a3, $77, $91, $79, $63
	.byte .lobyte(@env15), .hibyte(@env15), $64, $1d, $8f, $1f, $8f, $21, $8f, $23, $87, $88, $23, $8f, $78, $99, $79, $86, $23
	.byte $8f, $24, $8f, $23, $8f, $21, $8f, $1f, $8f, $1f, $87, $88, $61, $f5, $1f, $21, $97, $63, .lobyte(@env34), .hibyte(@env34)
	.byte $62, $21, $c5, $62, $61, $1e, $21, $1a, $a1, $6b, $7b, $63, .lobyte(@env15), .hibyte(@env15), $64, $86
@song0ref785:
	.byte $10, $e9, $10, $a1, $10, $e9, $10, $a1, $0e, $e9, $0e, $a1, $0e, $c5, $0e, $a1, $0e, $a1, $6b, $63, .lobyte(@env15)
	.byte .hibyte(@env15), $64, $10, $e9, $10, $a1, $10, $e9, $10, $a1, $13, $e9, $13, $a1, $13, $c5, $13, $a1, $12, $a1, $6b
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $24
	.word @song0ref785
	.byte $6b, $79
@song0ref836:
	.byte $10, $a1, $1c, $8f, $1c, $b3, $1c, $8f, $1c, $8f, $10, $a1, $1c, $a1, $10, $a1, $1c, $a1, $0e, $a1, $1a, $8f, $1a, $b3
	.byte $1a, $8f, $1a, $8f, $0e, $a1, $1a, $a1, $0e, $a1, $1a, $a1, $6b
	.byte $ff, $12
	.word @song0ref836
@song0ref876:
	.byte $13, $a1, $1f, $8f, $1f, $b3, $1f, $8f, $1f, $8f, $13, $a1, $1f, $a1, $13, $a1, $1e, $a1, $6b
	.byte $ff, $24
	.word @song0ref836
	.byte $6b
	.byte $ff, $12
	.word @song0ref836
	.byte $ff, $12
	.word @song0ref876
	.byte $6b
	.byte $ff, $24
	.word @song0ref836
	.byte $6b
	.byte $ff, $12
	.word @song0ref836
	.byte $ff, $12
	.word @song0ref876
	.byte $6b
	.byte $ff, $24
	.word @song0ref836
	.byte $6b
	.byte $ff, $12
	.word @song0ref836
	.byte $ff, $12
	.word @song0ref876
	.byte $6b
	.byte $ff, $24
	.word @song0ref836
	.byte $6b
	.byte $ff, $12
	.word @song0ref836
	.byte $ff, $12
	.word @song0ref876
	.byte $6b
	.byte $ff, $24
	.word @song0ref836
	.byte $6b
	.byte $ff, $12
	.word @song0ref836
	.byte $ff, $12
	.word @song0ref876
	.byte $6b
	.byte $ff, $24
	.word @song0ref836
	.byte $6b
	.byte $ff, $12
	.word @song0ref836
	.byte $ff, $12
	.word @song0ref876
	.byte $6b
	.byte $ff, $24
	.word @song0ref836
	.byte $6b
	.byte $ff, $12
	.word @song0ref836
	.byte $ff, $12
	.word @song0ref876
	.byte $fd
	.word @song0ch0loop
@song0ch1:
	.byte $00, $f7, $f7, $f7, $f7, $dd, $00, $f7, $f7, $f7, $f7, $dd
@song0ref986:
	.byte $a3, $75
@song0ref988:
	.byte $65, .lobyte(@env27), .hibyte(@env27)
@song0ref991:
	.byte $69, $01, $80, $34, $b3, $67, $34, $a1, $67, $34, $b3, $67, $34, $a1, $65, .lobyte(@env7), .hibyte(@env7), $82, $37
	.byte $e9, $65, .lobyte(@env27), .hibyte(@env27), $80, $34, $b3, $67, $34, $a1, $67, $34, $b3, $67, $34, $a1, $65, .lobyte(@env7)
	.byte .hibyte(@env7), $82, $32, $c5, $a3, $65, .lobyte(@env27), .hibyte(@env27), $80, $34, $b3, $67, $34, $a1, $67, $34, $b3
	.byte $67, $34, $a1, $67, $82, $28, $c5, $76, $67, $69, $01, $88, $34, $8f, $91, $75, $91, $91, $74, $91, $91, $73, $91, $91
	.byte $76, $65, .lobyte(@env7), .hibyte(@env7), $69, $01, $32, $8f, $91, $75, $91, $91, $74, $91, $91, $73, $91, $91
@song0ch1loop:
	.byte $66
	.byte $ff, $16
	.word @song0ref986
	.byte $ff, $15
	.word @song0ref988
	.byte $ff, $31
	.word @song0ref988
@song0ref1098:
	.byte $77, $65, .lobyte(@env0), .hibyte(@env0), $66
@song0ref1103:
	.byte $32, $87, $61, $fb, $32, $34, $8f, $62, $34, $a9, $63, .lobyte(@env32), .hibyte(@env32), $c7, $63, .lobyte(@env34)
	.byte .hibyte(@env34), $a3, $63, .lobyte(@env15), .hibyte(@env15), $64, $2f, $a1, $34, $a1, $2f, $a1, $34, $a1, $61, $e9
	.byte $34, $39, $87, $62, $39, $85, $34, $b3, $63, .lobyte(@env32), .hibyte(@env32), $c7, $63, .lobyte(@env34), .hibyte(@env34)
	.byte $a3, $00, $a1, $63, .lobyte(@env15), .hibyte(@env15), $64, $34, $87, $00, $85, $36, $87, $00, $85, $37, $a1, $63, .lobyte(@env32)
	.byte .hibyte(@env32), $c7, $63, .lobyte(@env33), .hibyte(@env33), $bf, $00, $85, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $37, $a1, $36, $a1, $34, $a1, $61, $f6, $34, $39, $8f, $62, $39, $8f, $61, $0f, $39, $32, $8f, $32, $87, $62, $32, $cd
	.byte $63, .lobyte(@env33), .hibyte(@env33), $eb, $62, $61, $1a, $32, $27, $99, $62, $61, $18, $27, $25, $85
	.byte $ff, $2e
	.word @song0ref1103
@song0ref1224:
	.byte $39, $8f, $39, $8f, $2f, $8f, $62, $3b, $d7, $63, .lobyte(@env33), .hibyte(@env33), $c7, $62, $61, $1d, $3b, $27, $a1
	.byte $75, $94, $27, $87, $76, $28, $85, $77, $29, $87, $78, $2a, $85, $79
@song0ref1257:
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $37, $8f, $36, $8f, $34, $8f, $30, $8f, $63, .lobyte(@env33), .hibyte(@env33)
	.byte $91, $62, $61, $04, $30, $2f, $8f, $63, .lobyte(@env15), .hibyte(@env15), $64, $37, $8f, $36, $8f, $34, $8f, $2f, $a1
	.byte $62, $61, $04, $2f, $2e, $8f, $65, .lobyte(@env23), .hibyte(@env23), $2f, $87, $00, $85, $67, $34, $87, $00, $85, $67
	.byte $36, $87, $00, $85, $67, $37, $87, $00, $85, $67, $39, $99, $63, .lobyte(@env32), .hibyte(@env32), $99, $63, .lobyte(@env15)
	.byte .hibyte(@env15), $64, $67, $37, $b3, $67, $34, $a1, $67, $37, $b3, $67, $36, $b3, $65, .lobyte(@env0), .hibyte(@env0)
	.byte $66, $34, $8f, $62, $61, $08, $34, $31, $8f
	.byte $ff, $25
	.word @song0ref1257
@song0ref1357:
	.byte $67, $3c, $99, $63, .lobyte(@env32), .hibyte(@env32), $99, $63, .lobyte(@env15), .hibyte(@env15), $64, $67, $3b, $b3
	.byte $67, $39, $a1, $67, $3b, $b3, $67, $39, $b3, $65, .lobyte(@env0), .hibyte(@env0), $66, $37, $8f, $62, $61, $07, $37
	.byte $34, $8f
	.byte $ff, $34
	.word @song0ref1257
	.byte $ff, $25
	.word @song0ref1257
@song0ref1398:
	.byte $78, $67, $96, $3c, $8f, $77, $89, $63, .lobyte(@env32), .hibyte(@env32), $87, $76, $91, $75, $91, $74, $91, $73, $91
	.byte $79, $63, .lobyte(@env15), .hibyte(@env15), $64, $67, $94, $39, $a1, $78, $67, $96, $3b, $8f, $77, $91, $76, $63, .lobyte(@env32)
	.byte .hibyte(@env32), $91, $75, $91, $74, $91, $73, $91, $72, $91, $71, $91, $78, $63, .lobyte(@env15), .hibyte(@env15)
	.byte $64, $67, $39, $8f, $77, $91, $76, $63, .lobyte(@env32), .hibyte(@env32), $91, $75, $91, $74, $91, $73, $91, $72, $91
	.byte $71, $f7, $a9, $70, $f7, $df, $74, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env27), .hibyte(@env27)
	.byte $69, $00, $88, $34, $87, $71, $87, $75, $67, $69, $00, $34, $87, $71, $87, $76, $67, $69, $01, $34, $87, $71, $87, $77
	.byte $67, $69, $02, $34, $87, $71, $87, $a3, $75, $67
	.byte $ff, $15
	.word @song0ref991
	.byte $ff, $15
	.word @song0ref988
	.byte $ff, $15
	.word @song0ref988
	.byte $ff, $15
	.word @song0ref988
	.byte $ff, $15
	.word @song0ref988
	.byte $ff, $15
	.word @song0ref988
	.byte $ff, $15
	.word @song0ref988
	.byte $ff, $14
	.word @song0ref988
	.byte $76, $65, .lobyte(@env27), .hibyte(@env27), $88
@song0ref1548:
	.byte $28, $c5, $75, $c7, $74, $c7, $73, $c7, $76, $67, $26, $c5, $75, $c7, $74, $c7, $73, $c7, $76, $67, $28, $c5, $75, $c7
	.byte $74, $c7, $73, $c7, $76, $67, $2b, $c5, $75, $c7, $74, $c7, $73, $c7, $76, $67
	.byte $ff, $14
	.word @song0ref1548
	.byte $76, $67
	.byte $ff, $14
	.word @song0ref1548
	.byte $76, $67
	.byte $ff, $14
	.word @song0ref1548
	.byte $00, $f7, $f7, $f7, $f7, $dd, $00, $f7, $f7, $f7, $f7, $dd
	.byte $ff, $3d
	.word @song0ref1098
	.byte $ff, $2e
	.word @song0ref1103
	.byte $ff, $47
	.word @song0ref1224
	.byte $ff, $25
	.word @song0ref1257
	.byte $ff, $0f
	.word @song0ref1357
	.byte $ff, $34
	.word @song0ref1257
	.byte $ff, $25
	.word @song0ref1257
	.byte $ff, $1d
	.word @song0ref1398
	.byte $70, $00, $f7, $f7, $ad, $f7, $f7, $f7, $f7, $97, $74, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env27)
	.byte .hibyte(@env27), $69, $00, $88, $34, $87, $71, $87, $75, $67, $69, $00, $34, $87, $71, $87, $76, $67, $69, $01, $34
	.byte $87, $71, $87, $77, $67, $69, $02, $34, $87, $71, $87, $fd
	.word @song0ch1loop
@song0ch2:
@song0ref1689:
	.byte $f7, $f7, $f7, $f7
@song0ref1693:
	.byte $df, $f7, $f7, $f7, $f7, $df, $f7, $f7, $f7, $f7, $df, $f7, $f7, $f7, $f7, $97, $9c, $2f, $8f, $2f, $8f, $2f, $8f, $2f
	.byte $8f
@song0ch2loop:
	.byte $9c
@song0ref1720:
	.byte $2c, $a1, $00, $a1, $2c, $a1, $00, $a1, $2c, $9f, $00, $a3
@song0ref1732:
	.byte $2c, $a1, $00, $a1, $2c, $8f, $00, $b3, $2c, $a1, $00, $a1, $2c, $8f, $00, $b3, $2c, $c5
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $2c, $8f, $00, $b3
	.byte $ff, $11
	.word @song0ref1732
@song0ref1763:
	.byte $a1, $00, $a1, $2c, $8f, $00, $b3, $2c, $8f, $2c, $8f, $2c, $8f, $2c, $8f
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $2c, $8f, $00, $b3
	.byte $ff, $11
	.word @song0ref1732
	.byte $ff, $0f
	.word @song0ref1763
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $2c, $8f, $00, $b3
	.byte $ff, $11
	.word @song0ref1732
	.byte $ff, $0f
	.word @song0ref1763
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $88, $10, $87, $00, $85, $10, $8f, $1c, $8f, $10, $99, $00, $85, $10, $8f
	.byte $1f, $8f, $1d, $8f, $1c, $a1, $1a, $e9
	.byte $ff, $11
	.word @song0ref486
	.byte $c5, $18, $a1, $86, $10, $87, $00, $85
	.byte $ff, $2e
	.word @song0ref517
	.byte $88, $1a, $a1, $0e, $8f, $1a, $a1, $0e, $8f, $1a, $8f, $18, $8f, $17, $8f, $15, $8f, $13, $8f, $11, $8f, $13, $c5, $17
	.byte $8f, $15, $8f, $13, $8f, $15, $8f, $13, $8f, $12, $8f, $13, $8f, $12, $8f, $10, $a1, $0e, $a1, $11, $c5, $13, $d7, $10
	.byte $8f, $11, $8f, $13, $8f, $15, $d7, $11, $8f, $13, $8f, $15, $8f, $17, $b3, $17, $8f, $18, $8f, $17, $8f, $15, $8f, $13
	.byte $8f, $15, $c5, $9c, $2c, $8f, $2c, $8f, $2c, $8f, $2c
@song0ref1955:
	.byte $8f, $2c, $8f, $00, $d7, $2c, $8f, $00, $8f, $2c, $8f, $00, $d7, $2c, $8f, $00
	.byte $ff, $10
	.word @song0ref1955
	.byte $ff, $10
	.word @song0ref1955
@song0ref1977:
	.byte $8f, $2c, $8f, $00, $d7, $2c, $8f, $00, $8f, $2c, $8f, $00, $b3, $2c, $8f, $00, $8f, $2c, $8f, $00
	.byte $ff, $10
	.word @song0ref1955
	.byte $ff, $10
	.word @song0ref1955
	.byte $ff, $10
	.word @song0ref1955
	.byte $ff, $14
	.word @song0ref1977
	.byte $8f
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $81, $00, $f7, $f7, $f7, $f7, $db, $f7, $f7, $f7, $f7, $df
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $2c, $8f, $00, $b3
	.byte $ff, $11
	.word @song0ref1732
	.byte $ff, $0f
	.word @song0ref1763
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $ff, $1e
	.word @song0ref1720
	.byte $2c, $8f, $00, $b3
	.byte $ff, $11
	.word @song0ref1732
	.byte $ff, $0f
	.word @song0ref1763
	.byte $fd
	.word @song0ch2loop
@song0ch3:
	.byte $9b, $70, $f7, $c3, $76, $6e, $fe, $00, $8c, $25, $c5, $00, $99, $f7, $c1, $74, $81, $6e, $ff, $10, $80, $22, $c3, $00
	.byte $9b, $70, $f7, $9f, $76, $6e, $fd, $30, $8c, $28, $8f, $00, $8f, $76, $6e, $fe, $00, $24, $c5, $00, $99, $f7, $f7, $93
	.byte $9b, $f7, $c3, $76, $6e, $fe, $00, $25, $c5, $00, $99, $f7, $c1, $74, $81, $6e, $ff, $10, $80, $22, $c3, $00, $f7, $bb
	.byte $76, $6e, $fd, $30, $8c, $28, $8f, $00, $8f, $76, $6e, $fe, $00, $24, $c5, $00, $99, $f7, $c3, $7a, $6e, $fc, $80, $90
	.byte $27, $8f, $7a, $6e, $fc, $80, $27, $8f, $7a, $6e, $fc, $80, $27, $8f, $7a, $6e, $fc, $80, $27, $8f
@song0ch3loop:
@song0ref2198:
	.byte $7a
@song0ref2199:
	.byte $8a, $31, $a1, $74, $8e
@song0ref2204:
	.byte $2e, $8f, $75, $2e, $8f
@song0ref2209:
	.byte $7a, $90, $27, $a1, $74, $8e, $2e, $8f, $75, $2e, $8f, $74
@song0ref2221:
	.byte $2e, $8f, $75, $2e, $8f, $74, $2e, $8f, $75, $2e, $8f, $7a, $90, $27, $a1, $74, $8e, $2e, $8f, $75, $2e, $8f, $74, $2e
	.byte $8f, $75, $2e, $8f, $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
@song0ref2269:
	.byte $74, $2e, $8f, $75, $2e, $8f, $7a, $90, $27, $a1, $74, $8e, $2e, $8f, $75, $2e, $8f, $74, $2e, $8f, $75, $2e, $8f, $77
	.byte $00, $a1
	.byte $ff, $18
	.word @song0ref2209
	.byte $74, $2e, $8f, $75, $2e, $8f, $7a, $90, $27, $8f, $27, $8f, $27, $8f, $27, $8f
	.byte $ff, $1e
	.word @song0ref2199
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $ff, $10
	.word @song0ref2269
	.byte $ff, $18
	.word @song0ref2209
	.byte $74, $2e, $8f, $75, $2e, $8f, $7a, $90, $27, $8f, $27, $8f, $27, $8f, $27, $8f
	.byte $ff, $1e
	.word @song0ref2199
	.byte $74
	.byte $ff, $18
	.word @song0ref2204
	.byte $ff, $1e
	.word @song0ref2198
	.byte $74
	.byte $ff, $18
	.word @song0ref2204
	.byte $ff, $1e
	.word @song0ref2198
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $ff, $10
	.word @song0ref2269
	.byte $ff, $18
	.word @song0ref2209
	.byte $74, $2e, $8f, $75, $2e, $8f, $7a, $90, $27, $8f, $27, $8f, $27, $8f, $27, $8f
	.byte $ff, $1e
	.word @song0ref2199
	.byte $74
	.byte $ff, $18
	.word @song0ref2204
	.byte $ff, $1e
	.word @song0ref2198
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $13
	.word @song0ref2204
	.byte $8f, $27, $8f, $27, $8f, $27, $8f, $77, $8e
@song0ref2481:
	.byte $2e, $c5, $74, $2e, $a1, $2e, $a1, $2e, $c5, $2e, $a1, $2e, $a1, $2e, $c5, $2e, $a1, $2e, $a1, $2e, $c5, $2e, $a1, $2e
	.byte $a1, $77
	.byte $ff, $18
	.word @song0ref2481
	.byte $77
	.byte $ff, $18
	.word @song0ref2481
	.byte $77
	.byte $ff, $18
	.word @song0ref2481
	.byte $ff, $1e
	.word @song0ref2198
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $18
	.word @song0ref2204
	.byte $74, $80
@song0ref2551:
	.byte $28, $87, $00, $97, $28, $87, $00, $97, $28, $8d, $00, $28, $87, $00, $85, $26, $8f, $28, $8b, $00, $93, $26, $8f, $00
	.byte $8f, $2a, $8f, $00, $8f, $28, $8f, $26, $a1, $00
	.byte $ff, $18
	.word @song0ref2551
	.byte $8d, $23, $8f, $00, $91, $28, $8d, $21, $a1
	.byte $ff, $22
	.word @song0ref2551
	.byte $ff, $14
	.word @song0ref2551
	.byte $91, $2a, $8f, $00, $8f, $2b, $8f, $00, $8d, $2d, $91, $21, $a1
	.byte $ff, $1e
	.word @song0ref2198
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $13
	.word @song0ref2204
	.byte $8f, $27, $8f, $27, $8f, $27, $8f, $74, $8e
	.byte $ff, $12
	.word @song0ref2221
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74, $2e, $8f, $75, $2e, $8f, $7a, $90, $27, $a1, $74, $8e, $2e, $8f, $75, $2e, $8f
	.byte $ff, $1e
	.word @song0ref2198
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $1c
	.word @song0ref2204
	.byte $74
	.byte $ff, $13
	.word @song0ref2204
	.byte $8f, $27, $8f, $27, $8f, $27, $8f, $fd
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $13
	.word @song0ref1689
	.byte $df
@song0ch4loop:
	.byte $ff, $13
	.word @song0ref1689
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $ff, $0f
	.word @song0ref1693
	.byte $df, $f7, $f7, $f7, $f7, $df, $fd
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $66, $6a, .lobyte(@tempo_env_4_3_4_3_4_3_3_3_mid), .hibyte(@tempo_env_4_3_4_3_4_3_3_3_mid), $00, $f7, $f7, $f7, $c5
	.byte $6b, $00, $f7, $f7, $f7, $c5, $6b, $7a, $86, $15, $b3, $21, $99, $15, $85, $00, $83, $15, $83, $00, $83, $79, $69, $02
	.byte $88, $15, $a7, $69, $02, $61, $80, $15, $21, $89, $62, $21, $99, $61, $13, $21, $1f, $8b, $62, $1f, $89, $63, .lobyte(@env34)
	.byte .hibyte(@env34), $a9
@song1ref60:
	.byte $62, $61, $0b, $1f, $1e, $89, $7a, $63, .lobyte(@env15), .hibyte(@env15), $64, $86, $1f, $99, $13, $85, $00, $83, $13
	.byte $83, $00, $83, $13, $a7, $79, $15, $a5, $7a, $17
@song1ref89:
	.byte $97, $6b, $15, $b3, $21, $99, $15, $85, $00, $83, $15, $83, $00, $83, $79, $69, $02, $88, $15, $a7, $69, $02, $61, $80
	.byte $15, $21, $89, $62, $21, $99, $61, $13, $21, $1f, $8b, $62, $1f, $89, $63, .lobyte(@env34), .hibyte(@env34), $a9, $62
	.byte $61, $66, $1f, $17, $89, $7a, $63, .lobyte(@env15), .hibyte(@env15), $64, $86, $1f, $99, $13, $91, $00, $83, $13, $a7
	.byte $79, $11, $a5, $7a, $10
	.byte $ff, $18
	.word @song1ref89
	.byte $ff, $36
	.word @song1ref60
	.byte $ff, $18
	.word @song1ref89
	.byte $ff, $36
	.word @song1ref60
	.byte $97, $6b, $78
@song1ref171:
	.byte $15, $99, $21, $85, $00, $83, $21, $83, $00, $83, $21, $93, $00, $83, $21, $b3, $15, $97, $88, $61, $de, $15, $17, $8b
	.byte $62, $17, $8b, $61, $22, $17, $15, $8b, $62, $15, $89, $86, $13, $99, $1f, $85, $00, $83, $1f, $83, $00, $83, $1f, $93
	.byte $00, $83, $1f, $b3, $13, $97, $88, $61, $da, $13, $15, $8b, $62, $15, $8b, $61, $de, $15, $17, $8b, $62, $17, $89, $6b
	.byte $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
@song1ref307:
	.byte $6b, $63, .lobyte(@env15), .hibyte(@env15), $64
@song1ref312:
	.byte $86, $15, $99, $21, $85, $00, $83, $21, $83, $00, $83, $21, $93, $00, $83, $21, $97, $77, $63, .lobyte(@env15), .hibyte(@env15)
	.byte $64, $65, .lobyte(@env7), .hibyte(@env7), $84, $2b, $a7, $65, .lobyte(@env27), .hibyte(@env27), $2d, $a5, $65, .lobyte(@env7)
	.byte .hibyte(@env7), $29, $97, $78, $65, .lobyte(@env0), .hibyte(@env0), $66, $86, $13, $99, $1f, $85, $00, $83, $1f, $83
	.byte $00, $83, $1f, $93, $00, $83, $1f, $97, $65, .lobyte(@env7), .hibyte(@env7), $84, $29, $a7, $67, $2b, $a5, $67, $2b
	.byte $97, $6b, $65, .lobyte(@env0), .hibyte(@env0), $66, $86, $15, $99, $21, $85, $00, $83, $21, $83, $00, $83, $21, $93
	.byte $00, $83, $21, $97, $77, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7), $80, $2b
	.byte $a7, $65, .lobyte(@env27), .hibyte(@env27), $2d, $a5, $65, .lobyte(@env7), .hibyte(@env7), $29, $97, $78, $65, .lobyte(@env0)
	.byte .hibyte(@env0), $66, $86, $13, $99, $1f, $85, $00, $83, $1f, $83, $00, $83, $1f, $93, $00, $83, $1f, $97, $65, .lobyte(@env7)
	.byte .hibyte(@env7), $80, $29, $a7, $65, .lobyte(@env27), .hibyte(@env27), $28, $a5, $67, $28
@song1ref462:
	.byte $97, $6b, $65, .lobyte(@env0), .hibyte(@env0), $66, $86, $13, $99, $1f, $85, $00, $83, $1f, $83, $00, $83, $1f, $93
	.byte $00, $83, $1f, $97, $77, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7), $80, $29
	.byte $a7, $65, .lobyte(@env27), .hibyte(@env27), $2b, $a5, $65, .lobyte(@env7), .hibyte(@env7), $27, $97, $78, $65, .lobyte(@env0)
	.byte .hibyte(@env0), $66, $86, $11, $99, $1d, $85, $00, $83, $1d, $83, $00, $83, $1d, $93, $00, $83, $1d, $97, $65, .lobyte(@env7)
	.byte .hibyte(@env7), $80, $27, $a7, $65, .lobyte(@env27), .hibyte(@env27), $26, $a5, $67, $26
	.byte $ff, $2c
	.word @song1ref462
	.byte $97, $6b, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env0), .hibyte(@env0), $66
	.byte $ff, $83
	.word @song1ref312
	.byte $ff, $2c
	.word @song1ref462
	.byte $97, $6b, $65, .lobyte(@env0), .hibyte(@env0), $66
@song1ref566:
	.byte $86, $13, $99, $1f, $85, $00, $83, $1f, $83, $00, $83, $1f, $93, $00, $83, $1f, $b3, $13, $97, $88, $61, $da, $13, $15
	.byte $8b, $62, $15, $8b
@song1ref594:
	.byte $61, $26, $15, $13, $8b, $62, $13, $89, $86, $11, $99, $1d, $85, $00, $83, $1d, $83, $00, $83, $1d, $93, $00, $83, $1d
	.byte $b3, $11, $97, $88, $61, $e2, $11, $13, $93, $62, $13, $83, $61, $da, $13, $15, $8b, $62, $15, $89, $6b
	.byte $ff, $34
	.word @song1ref566
	.byte $6b
	.byte $ff, $34
	.word @song1ref566
	.byte $6b
	.byte $ff, $34
	.word @song1ref566
	.byte $6b
	.byte $ff, $34
	.word @song1ref566
	.byte $6b
	.byte $ff, $34
	.word @song1ref566
	.byte $6b
	.byte $ff, $34
	.word @song1ref566
	.byte $6b
	.byte $ff, $34
	.word @song1ref566
@song1ref666:
	.byte $6b, $86, $61, $26, $15, $13, $8b, $62, $13, $8b, $61, $a8, $13, $15, $85, $00, $83, $1f, $83, $00, $83, $1f, $93, $00
	.byte $83, $1f, $b3, $61, $24, $1f, $19, $97, $88, $61, $2d, $19, $15, $93, $62, $15, $83
	.byte $ff, $1e
	.word @song1ref594
	.byte $ff, $18
	.word @song1ref666
	.byte $ff, $1e
	.word @song1ref594
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $6b, $86
	.byte $ff, $34
	.word @song1ref171
	.byte $ff, $58
	.word @song1ref307
	.byte $6b, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env0), .hibyte(@env0), $66
	.byte $ff, $58
	.word @song1ref312
	.byte $6b, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env0), .hibyte(@env0), $66
	.byte $ff, $58
	.word @song1ref312
	.byte $6b, $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env0), .hibyte(@env0), $66
	.byte $ff, $58
	.word @song1ref312
	.byte $fd
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $66, $63, .lobyte(@env15), .hibyte(@env15), $64, $00, $f7, $f7, $f7, $c5, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $00, $f7, $f7, $f7, $c5, $63, .lobyte(@env15), .hibyte(@env15), $64, $00, $f7, $f7, $f7, $c5, $63, .lobyte(@env15)
	.byte .hibyte(@env15), $64, $00, $f7, $f7, $f7, $c5, $b5, $79, $65, .lobyte(@env27), .hibyte(@env27), $80
@song1ref832:
	.byte $2d, $b3, $65, .lobyte(@env7), .hibyte(@env7), $2b, $a7, $65, .lobyte(@env27), .hibyte(@env27), $2d, $a5, $65, .lobyte(@env7)
	.byte .hibyte(@env7), $29, $cd, $67, $29, $b3, $67, $29, $a7, $67, $2b, $a5, $67, $2b, $97, $b5, $65, .lobyte(@env27), .hibyte(@env27)
	.byte $2d, $b3, $65, .lobyte(@env7), .hibyte(@env7), $2b, $a7, $65, .lobyte(@env27), .hibyte(@env27), $2d, $a5, $65, .lobyte(@env7)
	.byte .hibyte(@env7), $29, $cd, $67, $29, $b3, $67, $29, $a7, $65, .lobyte(@env27), .hibyte(@env27), $28, $a5, $67, $28, $97
	.byte $b5, $67
	.byte $ff, $21
	.word @song1ref832
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env0), .hibyte(@env0), $66
@song1ref909:
	.byte $98, $2d, $a7, $69, $01, $88, $61, $1a, $2d, $28, $89, $62, $28, $99, $69, $00, $98, $2d, $97, $63, .lobyte(@env34)
	.byte .hibyte(@env34), $9b, $63, .lobyte(@env15), .hibyte(@env15), $64, $28, $97, $2d, $8b, $69, $00, $9a, $61, $ec, $2d
	.byte $2f, $85, $62, $2f, $83, $69, $01, $61, $f9, $2f, $30, $85, $62, $30, $83, $69, $02, $61, $f4, $30, $32, $83, $62, $32
	.byte $83, $69, $01, $98, $30, $99, $63, .lobyte(@env34), .hibyte(@env34), $8d, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $69, $00, $2f, $a5, $69, $01, $2b, $97, $78, $63, .lobyte(@env33), .hibyte(@env33), $8d, $77, $8d, $76, $8d, $75, $8b
	.byte $74, $8d, $73, $8d, $78, $63, .lobyte(@env15), .hibyte(@env15), $64, $69, $01, $9a, $28, $85, $00, $83, $28, $83, $00
	.byte $83, $79
	.byte $ff, $19
	.word @song1ref909
@song1ref1027:
	.byte $69, $01, $34, $99, $63, .lobyte(@env34), .hibyte(@env34), $8d, $63, .lobyte(@env15), .hibyte(@env15), $64, $69, $00
	.byte $88, $37, $a5, $69, $02, $34, $97, $78, $63, .lobyte(@env33), .hibyte(@env33), $8d, $77, $8d, $76, $8d, $75, $8b, $74
	.byte $8d, $73, $8d, $78, $63, .lobyte(@env15), .hibyte(@env15), $64, $69, $01, $9a, $2f, $97, $79, $69, $00, $32, $a7, $69
	.byte $01, $61, $f1, $32, $34, $83, $62, $34, $9f, $69, $02, $32, $97, $63, .lobyte(@env34), .hibyte(@env34), $eb, $63, .lobyte(@env15)
	.byte .hibyte(@env15), $64, $30, $a7, $69, $01, $61, $f0, $30, $32, $83, $62, $32, $9f, $69, $00, $30, $97, $63, .lobyte(@env34)
	.byte .hibyte(@env34), $eb, $63, .lobyte(@env15), .hibyte(@env15), $64, $69, $00, $2d, $a7, $69, $01, $61, $ec, $2d, $2f
	.byte $83, $62, $2f, $9f, $69, $02, $2d, $97, $63, .lobyte(@env34), .hibyte(@env34), $eb, $63, .lobyte(@env15), .hibyte(@env15)
	.byte $64, $2b, $a7, $69, $01, $61, $d6, $2b, $2f, $83, $62, $2f, $9f, $69, $00, $30, $97, $63, .lobyte(@env34), .hibyte(@env34)
	.byte $eb, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $2e
	.word @song1ref909
	.byte $79
	.byte $ff, $19
	.word @song1ref909
	.byte $ff, $27
	.word @song1ref1027
	.byte $69, $02, $32, $97, $63, .lobyte(@env34), .hibyte(@env34), $eb, $63, .lobyte(@env15), .hibyte(@env15), $64, $30, $a7
	.byte $69, $01, $61, $f0, $30, $32, $83, $62, $32, $9f, $69, $00, $37, $97, $63, .lobyte(@env34), .hibyte(@env34), $eb, $eb
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7), $80
@song1ref1225:
	.byte $2b, $a7, $65, .lobyte(@env27), .hibyte(@env27), $2d, $a5, $65, .lobyte(@env7), .hibyte(@env7), $29, $f7, $8b, $67
	.byte $29, $a7, $67, $2b, $a5, $67, $2b, $97, $eb, $67, $2b, $a7, $65, .lobyte(@env27), .hibyte(@env27), $2d, $a5, $65, .lobyte(@env7)
	.byte .hibyte(@env7), $29, $f7, $8b, $67, $29, $a7, $65, .lobyte(@env27), .hibyte(@env27), $28, $a5, $67, $28, $97, $eb, $63
	.byte .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7)
	.byte $ff, $1c
	.word @song1ref1225
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7)
	.byte $ff, $1b
	.word @song1ref1225
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env0), .hibyte(@env0), $66, $92
@song1ref1303:
	.byte $2d, $8b, $73, $2d, $8b, $79, $21, $8b, $2d, $89, $2f, $8b, $73, $2f, $8b, $79, $2d, $8b, $2f, $89, $30, $8b, $73, $30
	.byte $8b, $79, $21, $8b, $2d, $89, $32, $8b, $30, $8b, $2f, $8b, $2b, $89, $2d, $8b, $73, $2d, $8b, $79, $21, $8b, $2d, $89
	.byte $2f, $8b, $73, $2f, $8b, $79, $2d, $8b, $2f, $89, $30, $8b, $73, $30, $8b, $79, $32, $8b, $34, $89, $35, $8b, $34, $8b
	.byte $32, $8b, $30, $89
	.byte $ff, $3e
	.word @song1ref1303
@song1ref1382:
	.byte $34
@song1ref1383:
	.byte $89, $2b, $8b, $73, $2b, $8b, $79, $1f, $8b, $2b, $89, $2d, $8b, $73, $2d, $8b, $79, $2b, $8b, $2d, $89, $2e, $8b, $73
	.byte $2e, $8b, $79, $1f, $8b, $2b, $89, $30, $8b, $2e, $8b, $2d, $8b, $29, $89, $2b, $8b, $73, $2b, $8b, $79, $1f, $8b, $2b
	.byte $89, $2d, $8b, $73, $2d, $8b, $79, $2b, $8b, $2d, $89, $2e, $8b, $73, $2e, $8b, $79, $30, $8b, $32, $89, $33, $8b, $32
	.byte $8b, $30, $8b, $32
	.byte $ff, $40
	.word @song1ref1383
	.byte $89, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $ff, $40
	.word @song1ref1303
	.byte $ff, $3e
	.word @song1ref1303
	.byte $ff, $41
	.word @song1ref1382
	.byte $ff, $3b
	.word @song1ref1383
	.byte $35, $8b, $37, $8b, $39, $89
@song1ref1485:
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64
@song1ref1489:
	.byte $98, $2b, $a7, $69, $01, $88, $61, $1e, $2b, $26, $89, $62, $26, $99, $69, $00, $98, $2b, $97, $63, .lobyte(@env34)
	.byte .hibyte(@env34), $9b, $63, .lobyte(@env15), .hibyte(@env15), $64, $26, $97, $2b, $8b, $69, $00, $9a, $61, $ea, $2b
	.byte $2d, $85, $62, $2d, $83, $69, $01, $61, $f8, $2d, $2e, $85, $62, $2e, $83, $69, $02, $61, $f2, $2e, $30, $83, $62, $30
	.byte $83, $69, $01, $98, $2e, $99, $63, .lobyte(@env34), .hibyte(@env34), $8d, $63, .lobyte(@env15), .hibyte(@env15), $64
	.byte $69, $00, $2d, $a5, $69, $01, $29, $97, $78, $63, .lobyte(@env33), .hibyte(@env33), $8d, $77, $8d, $76, $8d, $75, $8b
	.byte $74, $8d, $73, $8d, $78, $63, .lobyte(@env15), .hibyte(@env15), $64, $69, $01, $9a, $26, $85, $00, $83, $26, $83, $00
	.byte $83, $79
	.byte $ff, $19
	.word @song1ref1489
@song1ref1607:
	.byte $69, $01, $32, $99, $63, .lobyte(@env34), .hibyte(@env34), $8d, $63, .lobyte(@env15), .hibyte(@env15), $64, $69, $00
	.byte $88, $35, $a5, $69, $02, $32, $97, $78, $63, .lobyte(@env33), .hibyte(@env33), $8d, $77, $8d, $76, $8d, $75, $8b, $74
	.byte $8d, $73, $8d, $78, $63, .lobyte(@env15), .hibyte(@env15), $64, $69, $01, $9a, $2d, $97, $79, $69, $00, $30, $a7, $69
	.byte $01, $61, $f0, $30, $32, $83, $62, $32, $9f, $69, $02, $30, $97, $63, .lobyte(@env34), .hibyte(@env34), $eb, $63, .lobyte(@env15)
	.byte .hibyte(@env15), $64, $2e, $a7, $69, $01, $61, $ed, $2e, $30, $83, $62, $30, $9f, $69, $00, $2e, $97, $63, .lobyte(@env34)
	.byte .hibyte(@env34), $eb, $63, .lobyte(@env15), .hibyte(@env15), $64, $69, $00, $2b, $a7, $69, $01, $61, $ea, $2b, $2d
	.byte $83, $62, $2d, $9f, $69, $02, $2b, $97, $63, .lobyte(@env34), .hibyte(@env34), $eb, $63, .lobyte(@env15), .hibyte(@env15)
	.byte $64, $29, $a7, $69, $01, $61, $d1, $29, $2d, $83, $62, $2d, $9f, $69, $00, $2e, $97, $63, .lobyte(@env34), .hibyte(@env34)
	.byte $eb
	.byte $ff, $2e
	.word @song1ref1485
	.byte $79
	.byte $ff, $19
	.word @song1ref1489
	.byte $ff, $27
	.word @song1ref1607
	.byte $69, $02, $30, $97, $63, .lobyte(@env34), .hibyte(@env34), $eb, $63, .lobyte(@env15), .hibyte(@env15), $64, $2e, $a7
	.byte $69, $01, $61, $ed, $2e, $30, $83, $62, $30, $9f, $69, $00, $35, $97, $63, .lobyte(@env34), .hibyte(@env34), $eb, $eb
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7), $80, $29, $a7, $65, .lobyte(@env27)
	.byte .hibyte(@env27), $2b, $a5, $65, .lobyte(@env7), .hibyte(@env7), $27, $f7, $8b, $67, $27, $a7, $67, $29, $a5, $67, $29
	.byte $97, $eb, $67, $29, $a7, $65, .lobyte(@env27), .hibyte(@env27), $2b, $a5, $65, .lobyte(@env7), .hibyte(@env7), $27
	.byte $f7, $8b, $67, $27, $a7, $65, .lobyte(@env27), .hibyte(@env27), $26, $a5, $67, $26, $97, $eb, $63, .lobyte(@env15)
	.byte .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7)
	.byte $ff, $1c
	.word @song1ref1225
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7)
	.byte $ff, $1c
	.word @song1ref1225
	.byte $63, .lobyte(@env15), .hibyte(@env15), $64, $65, .lobyte(@env7), .hibyte(@env7)
	.byte $ff, $1b
	.word @song1ref1225
	.byte $7a, $63, .lobyte(@env35), .hibyte(@env35), $65, .lobyte(@env0), .hibyte(@env0), $66, $69, $00, $88
@song1ref1891:
	.byte $2d, $99, $69, $01, $21, $97, $69, $00, $2f, $99, $69, $01, $23, $97, $69, $02, $30, $99, $69, $00, $24, $97, $69, $01
	.byte $32, $99, $69, $00, $26, $85, $69, $01, $85, $69, $02, $85, $69, $01, $85, $69, $00, $87, $79, $85, $78, $87, $77, $85
	.byte $7b, $69, $01, $26, $97, $69, $00, $32, $99, $26, $97, $69, $02, $30, $99, $69, $00, $2f, $97, $69, $01, $2d, $99, $69
	.byte $01, $2b, $97, $7a, $63, .lobyte(@env35), .hibyte(@env35), $69, $00
	.byte $ff, $1d
	.word @song1ref1891
	.byte $69, $02, $35, $99, $69, $00, $34, $97, $69, $01, $32, $99, $69, $00, $30, $97, $7a, $63, .lobyte(@env35), .hibyte(@env35)
	.byte $69, $00
	.byte $ff, $25
	.word @song1ref1891
	.byte $7a, $63, .lobyte(@env35), .hibyte(@env35), $69, $00
	.byte $ff, $19
	.word @song1ref1891
	.byte $69, $01, $39, $99, $69, $00, $37, $97, $69, $02, $35, $99, $69, $00, $34, $97, $69, $01, $35, $8b, $69, $02, $34, $8b
	.byte $69, $00, $32, $97, $7a, $63, .lobyte(@env35), .hibyte(@env35), $69, $00
	.byte $ff, $25
	.word @song1ref1891
	.byte $7a, $63, .lobyte(@env35), .hibyte(@env35), $69, $00
	.byte $ff, $1d
	.word @song1ref1891
	.byte $69, $02, $35, $99, $69, $00, $34, $97, $69, $01, $32, $99, $69, $00, $30, $97, $7a, $63, .lobyte(@env35), .hibyte(@env35)
	.byte $69, $00
	.byte $ff, $25
	.word @song1ref1891
	.byte $7a, $63, .lobyte(@env35), .hibyte(@env35), $69, $00
	.byte $ff, $19
	.word @song1ref1891
	.byte $69, $01, $39, $99, $69, $00, $37, $97, $69, $02, $35, $99, $69, $00, $34, $97, $69, $01, $35, $8b, $69, $02, $34, $8b
	.byte $69, $00, $32, $97, $fd
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $9e
@song1ref2122:
	.byte $2c, $b3, $2c, $8b, $00, $8b, $2c, $cd, $2c, $8b, $00, $a5, $2c, $b3, $2c, $8b, $00, $8b, $2c, $cd, $2c, $8b, $00, $a5
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
@song1ref2164:
	.byte $2c, $b3, $2c, $8b, $00, $8b, $2c, $cd, $2c, $8b, $00, $a5, $2c, $b3, $2c, $8b, $00, $8b, $2c, $cd, $2c, $8b, $2c, $8b
	.byte $2c, $8b, $2c, $89
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $18
	.word @song1ref2122
	.byte $ff, $1c
	.word @song1ref2164
	.byte $fd
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $9b, $75, $80
@song1ref2337:
	.byte $2b, $85, $00, $83, $2b, $83, $00, $83, $7a, $90, $29, $a7, $75, $80, $2b, $83, $00, $91, $2b, $85, $00, $83, $2b, $85
	.byte $00, $83, $2b, $83, $00, $83, $7a, $90, $29, $99, $75, $80, $2b, $85, $00, $83, $2b, $83, $00, $9f
	.byte $ff, $1c
	.word @song1ref2337
	.byte $75, $80, $2c, $85, $00, $83, $2b, $83, $00, $83, $9b
	.byte $ff, $24
	.word @song1ref2337
	.byte $ff, $1c
	.word @song1ref2337
	.byte $75, $80, $2c, $85, $00, $83, $2b, $83, $00, $83, $9b
	.byte $ff, $24
	.word @song1ref2337
	.byte $ff, $1c
	.word @song1ref2337
	.byte $75, $80, $2c, $85, $00, $83, $2b, $83, $00, $83, $9b
	.byte $ff, $24
	.word @song1ref2337
	.byte $ff, $1c
	.word @song1ref2337
	.byte $75, $80, $2c, $85, $00, $83, $2b, $83, $00, $83, $9b
	.byte $ff, $24
	.word @song1ref2337
	.byte $ff, $1c
	.word @song1ref2337
	.byte $75, $80, $2c, $85, $00, $83, $2b, $83, $00, $83, $9b
	.byte $ff, $24
	.word @song1ref2337
	.byte $ff, $1c
	.word @song1ref2337
	.byte $75, $80, $2c, $85, $00, $83, $2b, $83, $00, $83, $9b
	.byte $ff, $24
	.word @song1ref2337
	.byte $ff, $1c
	.word @song1ref2337
	.byte $75, $80, $2c, $85, $00, $83, $2b, $83, $00, $83, $9b
	.byte $ff, $24
	.word @song1ref2337
	.byte $2b, $85, $00, $83, $2b, $83, $00, $83, $7a, $90, $29, $a7, $75, $80, $2b, $83, $00, $83, $78, $8c, $29, $8b, $00, $8b
	.byte $24, $8b, $00, $89, $28, $85, $00, $83, $24, $85, $00, $83, $28, $85, $00, $83, $2a, $83, $00, $83
@song1ref2544:
	.byte $8a, $21, $99, $77, $8e
@song1ref2549:
	.byte $2e, $97
@song1ref2551:
	.byte $7a, $90, $29, $b3, $77, $8e, $2e, $8b, $2e, $8b, $2e, $97, $7a, $90, $29, $99, $77, $8e, $2e, $b3, $2e, $8b, $2e, $89
	.byte $7a, $90, $29, $b3, $77, $8e, $2e, $99, $2e, $97, $7a, $90, $29, $b3, $77, $8e, $2e, $99
	.byte $ff, $1c
	.word @song1ref2549
@song1ref2596:
	.byte $2e, $97, $7a, $90, $29, $b3, $76, $8c, $2a, $8b, $8e, $2e, $8b, $8c, $28, $85, $00, $83, $28, $83, $00, $83, $7a, $90
	.byte $29, $99, $76, $8c, $25, $8b, $00, $a5, $8e, $2e, $8b, $2e, $89, $7a, $90, $29, $b3, $76, $8c, $29, $8b, $00, $8b, $23
	.byte $85, $00, $83, $23, $83, $00, $83, $7a, $90, $29, $99, $77, $8c, $29, $8b, $00, $89, $8e, $2e, $99, $2e, $97, $7a, $90
	.byte $29, $b3, $76, $8c, $2a, $8b, $77, $8e, $2e, $8b, $76, $8c, $25, $85, $00, $83, $28, $83, $00, $83, $7a, $90, $29, $99
	.byte $75, $8c, $2b, $8b, $00, $a5, $77, $8e, $2e, $8b, $2e, $89, $76, $90, $29, $b3, $8c, $25, $8b, $00, $8b, $28, $85, $00
	.byte $83, $28, $83, $00, $83, $77, $90, $29, $8b, $76, $8c, $2a, $85, $00, $83, $27, $85, $00, $83, $2b, $83, $00, $83, $78
	.byte $ff, $1e
	.word @song1ref2544
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $66
	.word @song1ref2596
	.byte $75
@song1ref2750:
	.byte $26, $85, $00, $83, $26, $85, $00, $83, $28, $85, $00, $83, $2b, $83, $00, $83, $7a, $90, $29, $b3, $75, $8e, $2e, $8b
	.byte $2e, $8b, $2e, $97, $7a, $90, $29, $99, $75, $8c, $28, $85, $00, $83, $28, $83, $00, $83, $2a, $85, $00, $83, $2a, $85
	.byte $00, $83, $27, $85, $00, $83, $23, $83, $00, $83, $7a, $90, $29, $b3, $75, $8e, $2e, $99, $76, $8c, $27, $85, $00, $83
	.byte $27, $83, $00, $83, $7a, $90, $29, $b3, $75, $8c, $27, $85, $00, $83, $2c, $85, $00, $83, $2e, $85, $00, $83, $29, $83
	.byte $00, $83, $7a, $90, $29, $b3, $75, $8e, $2e, $8b, $2e, $8b, $2e, $97, $7a, $90, $29, $99, $75, $8c, $25, $85, $00, $83
	.byte $29, $83, $00, $83, $2b, $85, $00, $83, $2a, $85, $00, $83, $2b, $85, $00, $83, $27, $83, $00, $83, $7a, $90, $29, $b3
	.byte $75, $8e, $2e, $99, $76, $8c, $25, $85, $00, $83, $29, $83, $00, $83, $7a, $90, $29, $b3, $75, $8c
	.byte $ff, $62
	.word @song1ref2750
@song1ref2917:
	.byte $77, $2b, $85, $71, $85, $77, $87, $71, $85, $77, $87, $71, $85, $77, $85, $71, $85, $7a, $90, $29, $85, $71, $85, $76
	.byte $87, $71, $85, $77, $8c, $2b, $85, $71, $85, $76, $85, $71, $85, $75, $87, $71, $85, $75, $87, $71, $85, $75, $87, $71
	.byte $85, $75, $85, $71, $85, $7a, $90, $29, $85, $71, $85, $74, $87, $71, $85, $77, $8c, $2b, $85, $71, $85, $74, $85, $71
	.byte $85, $73, $87, $71, $85, $73, $87, $71, $85, $73, $87, $71, $85, $73, $85, $71, $85
	.byte $ff, $1a
	.word @song1ref2551
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $77, $8e, $2e, $99
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $77, $8e, $2e, $99
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $77, $8e, $2e, $99
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $77, $8e, $2e, $99
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $78
	.byte $ff, $1e
	.word @song1ref2544
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $66
	.word @song1ref2596
	.byte $78
	.byte $ff, $1e
	.word @song1ref2544
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $66
	.word @song1ref2596
	.byte $77, $8e, $2e, $99
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $77, $8e, $2e, $99
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $75, $8c
	.byte $ff, $80
	.word @song1ref2750
	.byte $75, $8c
	.byte $ff, $62
	.word @song1ref2750
	.byte $ff, $25
	.word @song1ref2917
	.byte $78
	.byte $ff, $1e
	.word @song1ref2544
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $78
	.byte $ff, $1e
	.word @song1ref2544
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $1c
	.word @song1ref2549
	.byte $ff, $19
	.word @song1ref2549
	.byte $8b, $29, $8b, $29, $8b, $29, $89, $fd
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref3198:
	.byte $f7, $f7, $f7, $c7, $f7, $f7, $f7, $c7, $f7, $f7, $f7, $c7, $f7, $f7, $f7, $c7, $f7, $f7, $f7, $c7, $f7, $f7, $f7, $c7
	.byte $ff, $18
	.word @song1ref3198
	.byte $ff, $18
	.word @song1ref3198
	.byte $ff, $18
	.word @song1ref3198
	.byte $ff, $18
	.word @song1ref3198
	.byte $ff, $18
	.word @song1ref3198
	.byte $ff, $18
	.word @song1ref3198
	.byte $ff, $18
	.word @song1ref3198
	.byte $ff, $18
	.word @song1ref3198
	.byte $fd
	.word @song1ch4loop
