;this file for FamiStudio Sound Engine generated by FamiStudio

; Info: Header size : 47 bytes.
; Info: Instruments size : 382 bytes.
; Info: Tempo envelopes size : 22 bytes.
; Info: Song 'Robot Attack' size: 4073 bytes.
; Info: Song 'All Clear' size: 205 bytes.
; Info: Song 'End of the Line' size: 108 bytes.
; Info: Total assembly file size: 4837 bytes.
; Info: Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Info: Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Info: Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Info: Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Info: Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.

@music_data:
	.byte 3
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env_4_mid), .hibyte(@tempo_env_4_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4
	.byte .lobyte(@tempo_env_4_3_3_3_mid), .hibyte(@tempo_env_4_3_3_3_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4
	.byte .lobyte(@tempo_env_6_mid), .hibyte(@tempo_env_6_mid), 0, 0

@instruments:
	.word @env24,@env6,@env13,@env21
	.word @env2,@env0,@env12,@env10
	.word @env3,@env0,@env12,@env10
	.word @env14,@env0,@env12,@env10
	.word @env4,@env1,@env12,@env15
	.word @env16,@env25,@env17,@env10
	.word @env20,@env25,@env8,@env10
	.word @env2,@env25,@env8,@env10
	.word @env11,@env0,@env7,@env10
	.word @env23,@env19,@env13,@env10

@samples:
	; .byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$36,$0f,$40	;1 (bark)
	; .byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$22,$0f,$40	;2 (sd1)
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $d0,$ae,$bc,$c2,$00,$03
@env2:
	.byte $04,$cf,$7f,$00,$01
@env3:
	.byte $00,$c5,$c4,$c3,$02,$c2,$05,$c1,$03,$c0,$00,$09
@env4:
	.byte $00,$cd,$ca,$c8,$c6,$c4,$02,$c3,$02,$c2,$c2,$c1,$c0,$00,$0c
@env5:
	.byte $c0,$c4,$c7,$00,$00
@env6:
	.byte $cd,$c0,$00,$01
@env7:
	.byte $c1,$c1,$c2,$c2,$c1,$c1,$c0,$c0,$00,$00
@env8:
	.byte $c0,$c0,$c1,$c1,$c2,$c2,$c1,$c1,$00,$00
@env9:
	.byte $c0,$cc,$cc,$00,$00
@env10:
	.byte $00,$c0,$7f,$00,$01
@env11:
	.byte $00,$cf,$ce,$03,$cd,$02,$cc,$05,$cb,$02,$ca,$03,$c9,$06,$c8,$04,$c7,$03,$c6,$02,$c5,$0a,$c4,$04,$c3,$04,$c2,$c1,$c0,$00,$1c
@env12:
	.byte $7f,$00,$00
@env13:
	.byte $c2,$7f,$00,$00
@env14:
	.byte $00,$ce,$cc,$c8,$c7,$c4,$c0,$00,$06
@env15:
	.byte $00,$c8,$c6,$c5,$c2,$be,$ba,$b7,$95,$00,$08
@env16:
	.byte $00,$ce,$ce,$cd,$cd,$cc,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c6,$c6,$c5,$c3,$c0,$00,$12
@env17:
	.byte $c0,$c2,$00,$01
@env18:
	.byte $c0,$c0,$cc,$00,$00
@env19:
	.byte $c7,$c1,$bb,$b8,$b3,$af,$aa,$a6,$a3,$00,$08
@env20:
	.byte $00,$cf,$ce,$03,$cd,$04,$cc,$05,$cb,$02,$ca,$02,$c9,$c9,$c8,$c8,$c7,$03,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$00,$18
@env21:
	.byte $00,$c3,$c0,$00,$02
@env22:
	.byte $c0,$c3,$c7,$00,$00
@env23:
	.byte $00,$cf,$ce,$ce,$cd,$cd,$cc,$cb,$cb,$ca,$02,$c9,$c9,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$c2,$c0,$00,$15
@env24:
	.byte $00,$cf,$03,$ce,$cd,$cd,$cc,$cc,$cb,$ca,$c9,$c7,$c6,$c6,$c5,$c5,$c4,$00,$10
@env25:
	.byte $cc,$c0,$00,$01
@env26:
	.byte $00,$c0,$bf,$be,$be,$bf,$c1,$c2,$c2,$c1,$00,$01
@env27:
	.byte $00,$c0,$b9,$b5,$b6,$bc,$c4,$ca,$cb,$c7,$00,$01
@env28:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01
@tempo_env_4_mid:
	.byte $02,$06,$04,$80
@tempo_env_4_3_3_3_mid:
	.byte $02,$05,$06,$05,$05,$06,$05,$03,$05,$06,$05,$06,$05,$03,$80
@tempo_env_6_mid:
	.byte $03,$05,$80
@song0ch0:
@song0ch0loop:
	.byte $66, $6a, .lobyte(@tempo_env_4_mid), .hibyte(@tempo_env_4_mid)
@song0ref6:
	.byte $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b
	.byte $ff, $14
	.word @song0ref6
@song0ref33:
	.byte $6b, $7a, $63, .lobyte(@env10), .hibyte(@env10), $64, $90
@song0ref40:
	.byte $29, $f7, $85, $2b, $f7, $85, $2c, $9d, $61, $09, $2c, $2b, $85, $62, $2b, $95, $61, $0a, $2b, $29, $8d, $62, $29, $8d
	.byte $30, $9d, $63, .lobyte(@env26), .hibyte(@env26), $bf, $2c, $bd, $6b, $79, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $8e, $33, $9d, $77, $9f, $76, $9f, $75, $9f, $74, $63, .lobyte(@env26), .hibyte(@env26), $9f, $73, $9f, $72, $9f, $71
	.byte $9f, $79, $63, .lobyte(@env10), .hibyte(@env10), $64, $32, $9d, $77, $9f, $76, $9f, $75, $9f, $74, $63, .lobyte(@env26)
	.byte .hibyte(@env26), $9f, $73, $9f, $72, $9f, $71, $9f
	.byte $ff, $1e
	.word @song0ref33
	.byte $79, $63, .lobyte(@env10), .hibyte(@env10), $64, $35, $9d, $77, $9f, $76, $9f, $75, $9f, $74, $63, .lobyte(@env26)
	.byte .hibyte(@env26), $9f, $73, $9f, $72, $9f, $71, $9f
@song0ref149:
	.byte $6b, $97, $77, $00, $81, $8a, $33, $81, $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $00, $81, $82, $61
	.byte $ec, $33, $35, $81, $62, $35, $85, $73, $8a, $35, $8d, $78, $33, $8d, $73, $33, $8d, $78, $30, $8d, $73, $30, $8d, $78
	.byte $33, $8d, $73, $33, $8d, $77, $65, .lobyte(@env18), .hibyte(@env18), $69, $01, $8e, $35, $8d, $76, $8f, $75, $8f, $74
	.byte $8f, $73, $8f, $72, $8f, $71, $8f, $70, $f7, $97, $78, $65, .lobyte(@env0), .hibyte(@env0), $66, $8a, $31, $8d, $73
	.byte $31, $8d, $78, $32, $8d, $73, $32, $8d, $78, $33, $8d, $73, $33, $8d, $6b, $9f, $78, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $69, $00, $35, $8d, $73, $35, $8d, $78, $33, $8d, $73, $33, $8d, $78, $30, $8d, $73, $30, $8d, $78, $33, $85, $61
	.byte $f6, $33, $35, $85, $73, $35, $85, $62, $35, $85, $78, $35, $8d, $73, $35, $8d, $78, $33, $85, $77, $87, $75, $69, $02
	.byte $82, $33, $8d, $63, .lobyte(@env27), .hibyte(@env27), $8f, $62, $61, $1c, $33, $2b, $8d, $77, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $65, .lobyte(@env18), .hibyte(@env18), $69, $01, $8e, $35, $8d, $76, $8f, $75, $8f, $74, $8f
	.byte $73, $8f, $72, $8f, $71, $8f, $70, $a7, $77, $65, .lobyte(@env0), .hibyte(@env0), $66, $8a, $30, $85, $76, $82, $61
	.byte $fa, $30, $31, $85, $62, $31, $85, $73, $8a, $31, $8d, $76, $69, $02, $82, $32, $85, $74, $87, $73, $32, $85, $71, $87
	.byte $77, $69, $00, $33, $85, $74, $87, $33, $85, $71, $87
	.byte $ff, $3c
	.word @song0ref149
	.byte $78, $39, $85, $61, $fc, $39, $3a, $85, $73, $3a, $85, $62, $3a, $85, $78, $3a, $8d, $73, $3a, $8d, $78, $3c, $8d, $73
	.byte $3c, $8d, $78, $3a, $8d, $73, $3a, $8d, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env18), .hibyte(@env18)
	.byte $69, $01, $8e, $35, $8d, $76, $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $f7, $85, $6b
	.byte $ff, $14
	.word @song0ref6
	.byte $6b, $f7, $f7, $f7, $f7, $9f, $6b, $f7, $f7, $f7, $f7, $9f, $6b, $78, $63, .lobyte(@env26), .hibyte(@env26), $65, .lobyte(@env0)
	.byte .hibyte(@env0), $66, $69, $00, $82
@song0ref477:
	.byte $1d, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $29, $85, $75, $69, $01, $87, $74
	.byte $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $1d, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87
	.byte $78, $69, $00, $11, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $11, $85, $73, $69
	.byte $01, $87, $78, $69, $02, $11, $85, $73, $69, $01, $87, $78, $69, $00, $29, $85, $75, $69, $01, $87, $74, $69, $02, $87
	.byte $73, $69, $01, $87, $78, $69, $00, $1d, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00
	.byte $1b, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $63, .lobyte(@env26), .hibyte(@env26), $69
	.byte $00
	.byte $ff, $24
	.word @song0ref477
@song0ref620:
	.byte $77, $69, $00, $61, $19, $1b, $17, $85, $69, $01, $87, $69, $02, $87, $69, $01, $87, $6b, $78, $69, $00, $1b, $85, $75
	.byte $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $27, $85, $75, $69, $01, $87, $74, $69, $02, $87
	.byte $73, $69, $01, $87, $78, $69, $00, $25, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00
	.byte $24, $85, $75, $69, $01, $87, $74, $69, $02, $22, $85, $73, $69, $01, $87, $78, $69, $00, $87, $69, $01, $87, $77, $69
	.byte $02, $87, $69, $01, $87, $76, $69, $00, $87, $69, $01, $87, $75, $69, $02, $87, $69, $01, $87, $74, $69, $00, $87, $69
	.byte $01, $87, $73, $69, $02, $87, $69, $01, $87, $74, $69, $00, $16, $85, $75, $69, $01, $17, $85, $76, $69, $02, $18, $85
	.byte $77, $69, $01, $19, $85, $78
@song0ref770:
	.byte $69, $00, $1b, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $27, $85, $75, $69, $01
	.byte $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $1b, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69
	.byte $01, $87, $78, $69, $00, $0f, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $1b, $85
	.byte $73, $69, $01, $87, $78, $69, $02, $1b, $85, $73, $69, $01, $87, $78, $69, $00, $27, $85, $75, $69, $01, $87, $74, $69
	.byte $02, $87, $73, $69, $01, $87, $78, $69, $00, $1b, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78
	.byte $69, $00, $1a, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $6b, $78, $63, .lobyte(@env26), .hibyte(@env26)
	.byte $ff, $14
	.word @song0ref770
@song0ref914:
	.byte $78, $69, $00, $0f, $85, $73, $69, $01, $87, $78, $69, $02, $0f, $85, $73, $69, $01, $87, $78, $69, $00, $27, $85, $75
	.byte $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $1b, $85, $75, $69, $01, $87, $74, $69, $02, $87
	.byte $73, $69, $01, $87, $78, $69, $00, $19, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $63, .lobyte(@env26)
	.byte .hibyte(@env26)
	.byte $ff, $14
	.word @song0ref770
@song0ref990:
	.byte $78, $69, $00, $0f, $85, $73, $69, $01, $87, $78, $69, $02, $0f, $85, $73, $69, $01, $87, $78, $69, $00, $27, $85, $75
	.byte $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $1b, $85, $75, $69, $01, $87, $74, $69, $02, $87
	.byte $73, $69, $01, $87, $77, $69, $00, $61, $1c, $19, $15, $85, $69, $01, $87, $69, $02, $87, $69, $01, $87, $6b, $78, $69
	.byte $00, $19, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $25, $85, $75, $69, $01, $87
	.byte $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $23, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01
	.byte $87, $78, $69, $00, $22, $85, $75, $69, $01, $87, $74, $69, $02, $20, $85, $73, $69, $01, $87, $78, $69, $00, $87, $69
	.byte $01, $87, $77, $69, $02, $87, $69, $01, $87, $76, $69, $00, $87, $69, $01, $87, $75, $69, $02, $87, $69, $01, $87, $74
	.byte $69, $00, $87, $69, $01, $87, $73, $69, $02, $87, $69, $01, $87, $74, $69, $00, $14, $85, $75, $69, $01, $15, $85, $76
	.byte $69, $02, $16, $85, $77, $69, $01, $17, $85, $78, $69, $00, $19, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69
	.byte $01, $87, $78, $69, $00, $25, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $19, $85
	.byte $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $0d, $85, $75, $69, $01, $87, $74, $69, $02
	.byte $87, $73, $69, $01, $87, $78, $69, $00, $19, $85, $73, $69, $01, $87, $78, $69, $02, $19, $85, $73, $69, $01, $87, $78
	.byte $69, $00, $25, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $19, $85, $75, $69, $01
	.byte $87, $74, $69, $02, $87, $73, $69, $01, $87, $78, $69, $00, $18, $85, $75, $69, $01, $87, $74, $69, $02, $87, $73, $69
	.byte $01, $87, $6b, $78, $63, .lobyte(@env26), .hibyte(@env26), $69, $00
	.byte $ff, $29
	.word @song0ref477
	.byte $78, $63, .lobyte(@env26), .hibyte(@env26), $69, $00
	.byte $ff, $24
	.word @song0ref477
	.byte $ff, $57
	.word @song0ref620
	.byte $6b, $78, $63, .lobyte(@env26), .hibyte(@env26)
	.byte $ff, $14
	.word @song0ref770
	.byte $ff, $15
	.word @song0ref914
	.byte $78, $63, .lobyte(@env26), .hibyte(@env26)
	.byte $ff, $14
	.word @song0ref770
	.byte $ff, $67
	.word @song0ref990
@song0ref1371:
	.byte $6b, $72, $87, $71, $8f, $77, $8a, $31, $85, $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $82, $61, $f4
	.byte $31, $33, $85, $62, $33, $85, $73, $8a, $33, $8d, $78, $31, $8d, $73, $31, $8d, $78, $2e, $8d, $73, $2e, $8d, $78, $31
	.byte $8d, $73, $31, $8d, $77, $65, .lobyte(@env18), .hibyte(@env18), $69, $01, $8e, $33, $8d, $76, $8f, $75, $8f, $74, $8f
	.byte $73, $8f, $72, $8f, $71, $8f, $70, $f7, $97, $78, $65, .lobyte(@env0), .hibyte(@env0), $66, $8a, $2f, $8d, $73, $2f
	.byte $8d, $78, $30, $8d, $73, $30, $8d, $78, $31, $8d, $73, $31, $8d, $6b, $9f, $78, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $69, $00, $33, $8d, $73, $33, $8d, $78, $31, $8d, $73, $31, $8d, $78, $2e, $8d, $73, $2e, $8d, $78, $31, $85, $61
	.byte $f4, $31, $33, $85, $73, $33, $85, $62, $33, $85, $78, $33, $8d, $73, $33, $8d, $78, $31, $85, $77, $87, $75, $69, $02
	.byte $82, $31, $8d, $63, .lobyte(@env27), .hibyte(@env27), $8f, $62, $61, $1b, $31, $2a, $8d, $77, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $65, .lobyte(@env18), .hibyte(@env18), $69, $01, $8e, $33, $8d, $76, $8f, $75, $8f, $74, $8f
	.byte $73, $8f, $72, $8f, $71, $8f, $70, $a7, $77, $65, .lobyte(@env0), .hibyte(@env0), $66, $8a, $2e, $85, $76, $82, $61
	.byte $f9, $2e, $2f, $85, $62, $2f, $85, $73, $8a, $2f, $8d, $76, $69, $02, $82, $30, $85, $74, $87, $73, $30, $85, $71, $87
	.byte $77, $69, $00, $31, $85, $74, $87, $31, $85, $71, $87
	.byte $ff, $45
	.word @song0ref1371
	.byte $78, $35, $85, $77, $87, $75, $69, $02, $82, $35, $8d, $63, .lobyte(@env27), .hibyte(@env27), $8f, $62, $61, $1d, $35
	.byte $2c, $8d, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env18), .hibyte(@env18), $69, $01, $8e, $33
	.byte $8d, $76, $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $70, $af, $79, $65, .lobyte(@env0), .hibyte(@env0)
	.byte $66, $90, $25, $85, $78, $87, $77, $87, $76, $87, $79, $26, $85, $78, $87, $77, $87, $76, $87, $79, $28, $85, $78, $87
	.byte $77, $87, $76, $87, $6b, $7a, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $27
	.word @song0ref40
	.byte $ff, $1e
	.word @song0ref33
	.byte $79, $63, .lobyte(@env10), .hibyte(@env10), $64, $35, $9d, $77, $9f, $76, $9f, $75, $9f, $74, $63, .lobyte(@env26)
	.byte .hibyte(@env26), $9f, $73, $9f, $72, $9f, $71, $9f
	.byte $ff, $27
	.word @song0ref33
	.byte $ff, $1d
	.word @song0ref33
	.byte $75, $90, $31, $85, $76, $32, $85, $77, $33, $85, $78, $34, $85, $79, $63, .lobyte(@env10), .hibyte(@env10), $64, $8e
	.byte $35, $9d, $77, $9f, $76, $9f, $75, $9f, $74, $63, .lobyte(@env26), .hibyte(@env26), $9f, $73, $9f, $72, $9f, $71, $97
	.byte $70, $87, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $66
@song0ref1775:
	.byte $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f, $79, $65, .lobyte(@env22)
	.byte .hibyte(@env22), $69, $01, $82
@song0ref1802:
	.byte $29, $9d, $78, $9f, $77, $9f, $76, $9f, $75, $9f, $74, $9f, $73, $9f, $72, $9f, $65, .lobyte(@env5), .hibyte(@env5)
	.byte $69, $01, $27, $9d, $73, $9f, $74, $9f, $75, $9f, $76, $9f, $77, $9f, $78, $9f, $79, $8f, $7a, $8f, $79, $67, $69, $01
	.byte $25, $8d, $78, $8f, $77, $8f, $76, $8f, $75, $9f, $74, $9f, $73, $9f, $72, $9f, $71, $9f, $9f, $72, $65, .lobyte(@env22)
	.byte .hibyte(@env22), $69, $01, $24, $9d, $73, $9f, $74, $9f, $75, $9f, $76, $9f, $77, $9f, $78, $9f, $79, $8f, $7a, $8f
	.byte $79, $67, $69, $01
	.byte $ff, $1e
	.word @song0ref1802
	.byte $72, $67, $69, $01, $27, $9d, $73, $9f, $74, $9f, $75, $9f, $76, $9f, $77, $9f, $78, $9f, $79, $8f, $7a, $8f
@song0ref1917:
	.byte $00, $9d, $76, $65, .lobyte(@env22), .hibyte(@env22)
@song0ref1923:
	.byte $69, $00, $29, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $76, $67, $69, $00, $29, $8d, $75, $8f, $74, $8f
	.byte $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $ad, $76, $67
@song0ref1959:
	.byte $69, $00, $29, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $76, $67, $69, $00, $29, $8d, $75, $8f, $74, $8f
	.byte $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $8d, $9f, $76, $65, .lobyte(@env5), .hibyte(@env5)
@song0ref1998:
	.byte $69, $00, $27, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $76, $67, $69, $00, $27, $8d, $75, $8f, $74, $8f
	.byte $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $ad, $76, $65, .lobyte(@env22), .hibyte(@env22), $69, $00, $26, $8d, $75
	.byte $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $76, $67, $69, $00, $26, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71
	.byte $8f, $70, $8f, $00, $8d, $00, $9d, $76, $67
	.byte $ff, $34
	.word @song0ref1923
	.byte $76, $65, .lobyte(@env22), .hibyte(@env22)
	.byte $ff, $11
	.word @song0ref1959
	.byte $00, $9d, $76, $67
	.byte $ff, $34
	.word @song0ref1923
@song0ref2091:
	.byte $76, $67, $69, $00, $27, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $76, $67, $69, $00, $27, $8d, $75, $8f
	.byte $74, $8f, $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $8d
	.byte $ff, $36
	.word @song0ref1917
	.byte $76, $67, $69, $00, $27, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $76, $67, $69, $00, $29, $8d, $75, $8f
	.byte $74, $8f, $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $8d
	.byte $ff, $14
	.word @song0ref1775
	.byte $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f
	.byte $ff, $24
	.word @song0ref1917
	.byte $00, $9d, $76, $67
	.byte $ff, $23
	.word @song0ref1923
	.byte $76, $67
	.byte $ff, $11
	.word @song0ref1998
	.byte $ff, $11
	.word @song0ref2091
	.byte $9f, $76, $67
	.byte $ff, $11
	.word @song0ref1998
	.byte $ff, $11
	.word @song0ref2091
	.byte $00, $9d, $76, $67
	.byte $ff, $22
	.word @song0ref1923
	.byte $00, $9d, $76, $67
	.byte $ff, $23
	.word @song0ref1923
	.byte $76, $67
	.byte $ff, $11
	.word @song0ref1998
	.byte $ff, $11
	.word @song0ref2091
	.byte $9f, $76, $67
	.byte $ff, $11
	.word @song0ref1998
	.byte $ff, $11
	.word @song0ref2091
	.byte $9f, $76, $67
	.byte $ff, $11
	.word @song0ref1998
	.byte $ff, $11
	.word @song0ref2091
@song0ref2246:
	.byte $9f, $76, $65, .lobyte(@env5), .hibyte(@env5), $69, $00, $25, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f
	.byte $76, $67, $69, $00, $25, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $70, $8f, $00, $ad, $76, $67, $69, $00
	.byte $25, $8d, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $76, $67, $69, $00, $25, $8d, $75, $8f, $74, $8f, $73, $8f
	.byte $72, $8f, $71, $8f, $70, $8f, $00, $8d, $9f, $76, $65, .lobyte(@env22), .hibyte(@env22)
	.byte $ff, $11
	.word @song0ref1998
	.byte $ff, $11
	.word @song0ref2091
	.byte $ff, $23
	.word @song0ref2246
	.byte $ff, $49
	.word @song0ref1917
	.byte $76, $67
	.byte $ff, $34
	.word @song0ref1923
	.byte $76, $65, .lobyte(@env22), .hibyte(@env22)
	.byte $ff, $11
	.word @song0ref1959
	.byte $00, $9d, $76, $67
	.byte $ff, $47
	.word @song0ref1923
	.byte $76, $67
	.byte $ff, $34
	.word @song0ref1923
	.byte $76, $65, .lobyte(@env22), .hibyte(@env22)
	.byte $ff, $11
	.word @song0ref1959
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref2373:
	.byte $92
@song0ref2374:
	.byte $2e, $9d, $00, $9d, $2e, $dd, $2e, $8d, $00, $8d, $2e, $9d, $2e, $8d, $00, $8d, $2e, $9d, $00, $9d, $2e, $dd, $2e, $8d
	.byte $00, $8d, $2e, $9d, $2e, $8d, $00, $8d
	.byte $ff, $1e
	.word @song0ref2374
@song0ref2409:
	.byte $2e, $8d, $63, .lobyte(@env10), .hibyte(@env10), $64
@song0ref2415:
	.byte $2e, $85, $82, $11, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $00, $9d, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $92, $2e, $85, $82, $1d, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $11, $bd, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $92, $2e, $8d, $00, $8d, $63, .lobyte(@env10), .hibyte(@env10), $64, $2e, $85, $82, $1d, $85, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2e, $85, $82, $11, $85, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2e, $85, $82, $11, $95, $00, $9d, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $92, $2e, $85, $82, $1d, $85, $63, .lobyte(@env28), .hibyte(@env28), $cf, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $92, $2e, $85, $82, $19, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $92, $2e, $85, $82, $1b, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $92, $2e, $85, $82, $1d, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $92
	.byte $ff, $33
	.word @song0ref2415
	.byte $63, .lobyte(@env28), .hibyte(@env28), $82, $1d, $85
@song0ref2560:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2e
@song0ref2566:
	.byte $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $1d, $85
@song0ref2573:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92
@song0ref2578:
	.byte $2e, $85, $82, $11, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $00, $9d, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $92, $2e, $8d, $00, $8d, $82, $11, $8d, $63, .lobyte(@env28), .hibyte(@env28), $af, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $92, $2e, $8d, $00, $8d, $2e, $9d, $2e, $85, $82, $11, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $92, $2e, $85, $82, $11, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $00, $9d, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $92, $2e, $8d, $00, $8d, $82, $11, $8d, $63, .lobyte(@env28), .hibyte(@env28), $af, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $92, $2e, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $19, $95, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $92, $2e, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $1b, $95, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $92, $2e, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $1b, $85, $1d, $8d
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $33
	.word @song0ref2573
	.byte $ff, $39
	.word @song0ref2560
@song0ref2710:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $0f, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f
	.byte $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $8d, $00, $8d, $82, $0f, $8d, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $af, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $8d, $00, $8d, $2c, $9d, $2c, $85, $82
	.byte $0f, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2b, $85, $82
	.byte $0e, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2b
	.byte $8d, $00, $8d, $82, $0e, $8d, $63, .lobyte(@env28), .hibyte(@env28), $af, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $92, $2b, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $19, $95, $63, .lobyte(@env10), .hibyte(@env10), $64, $92
	.byte $2b, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $1d, $95, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2b
	.byte $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $1a, $85, $1b, $8d
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $19
	.word @song0ref2710
@song0ref2841:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2e, $85, $82, $11, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f
	.byte $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2e, $8d, $00, $8d, $82, $11, $8d, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $af, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2e, $85, $63, .lobyte(@env28), .hibyte(@env28)
	.byte $84, $19, $95, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2e, $9d, $2e, $8d, $2e, $8d, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64
	.byte $ff, $35
	.word @song0ref2578
	.byte $ff, $19
	.word @song0ref2710
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $0f, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f
	.byte $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $8d, $00, $8d, $82, $0f, $8d, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $af, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $63, .lobyte(@env28), .hibyte(@env28)
	.byte $82, $19, $95, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $2c, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $1b, $85, $1d, $8d
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $16
	.word @song0ref2710
	.byte $82, $14, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85
	.byte $82, $16, $85, $63, .lobyte(@env28), .hibyte(@env28), $87, $63, .lobyte(@env28), .hibyte(@env28), $87, $00, $9d, $63
	.byte .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $8d, $00, $8d, $82, $16, $8d, $63, .lobyte(@env28), .hibyte(@env28)
	.byte $af, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $19, $95
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $19, $95, $63
	.byte .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $1b, $85, $1d, $8d
	.byte $ff, $20
	.word @song0ref2373
	.byte $ff, $1e
	.word @song0ref2374
	.byte $ff, $38
	.word @song0ref2409
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92
	.byte $ff, $33
	.word @song0ref2415
	.byte $63, .lobyte(@env28), .hibyte(@env28), $82, $1d, $85, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2e, $85, $63
	.byte .lobyte(@env28), .hibyte(@env28), $82, $1d, $85
@song0ref3099:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $0f, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f
	.byte $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $1b, $85, $63, .lobyte(@env28), .hibyte(@env28)
	.byte $8f, $0f, $bd, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $8d, $00, $8d, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $2c, $85, $82, $1b, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $92, $2c, $85, $82, $0f, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $92, $2c, $85, $82, $0f, $95, $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $1b, $85, $63
	.byte .lobyte(@env28), .hibyte(@env28), $cf, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $19, $85, $63
	.byte .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $1b, $85, $63
	.byte .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $1d, $85, $63
	.byte .lobyte(@env28), .hibyte(@env28), $8f
	.byte $ff, $35
	.word @song0ref3099
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c
	.byte $ff, $38
	.word @song0ref2566
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $19
	.word @song0ref2710
@song0ref3253:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $82, $0f, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f
	.byte $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $8d, $00, $8d, $82, $0f, $8d, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $af, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $63, .lobyte(@env28), .hibyte(@env28)
	.byte $82, $17, $95, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $63, .lobyte(@env28), .hibyte(@env28), $82
	.byte $19, $95, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2c, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $19
	.byte $85, $1b, $8d
	.byte $ff, $19
	.word @song0ref2710
	.byte $ff, $1c
	.word @song0ref3253
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $19
	.word @song0ref2710
	.byte $ff, $1c
	.word @song0ref3253
	.byte $ff, $19
	.word @song0ref2710
	.byte $ff, $1c
	.word @song0ref3253
	.byte $ff, $19
	.word @song0ref2710
	.byte $ff, $1c
	.word @song0ref3253
@song0ref3356:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2a, $85, $82, $0d, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f
	.byte $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2a, $8d, $00, $8d, $82, $0d, $8d, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $af, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2a, $8d, $00, $8d, $2a, $9d, $2a, $85, $82
	.byte $0d, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2a, $85, $82
	.byte $0d, $85, $63, .lobyte(@env28), .hibyte(@env28), $8f, $00, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $92, $2a
	.byte $8d, $00, $8d, $82, $0d, $8d, $63, .lobyte(@env28), .hibyte(@env28), $af, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $92, $2a, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $17, $95, $63, .lobyte(@env10), .hibyte(@env10), $64, $92
	.byte $2a, $9d, $63, .lobyte(@env10), .hibyte(@env10), $64, $2a, $85, $63, .lobyte(@env28), .hibyte(@env28), $82, $19, $85
	.byte $1b, $8d
	.byte $ff, $19
	.word @song0ref2710
	.byte $ff, $1c
	.word @song0ref3253
	.byte $ff, $33
	.word @song0ref3356
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $35
	.word @song0ref2710
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $19
	.word @song0ref2710
	.byte $ff, $18
	.word @song0ref2841
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $35
	.word @song0ref2578
	.byte $ff, $35
	.word @song0ref2710
	.byte $ff, $35
	.word @song0ref2573
	.byte $ff, $19
	.word @song0ref2710
	.byte $ff, $18
	.word @song0ref2841
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref3521:
	.byte $9f
@song0ref3522:
	.byte $77, $86
@song0ref3524:
	.byte $2d, $9d, $7a, $88, $29, $9d, $77, $86, $2d, $9d, $2d, $9d, $2d, $9d, $7a, $88, $29, $9d, $77, $86, $2d, $bd, $2d, $9d
	.byte $7a, $88, $29, $9d, $77, $86, $2d, $9d, $2d, $9d, $2d, $9d, $7a, $88, $29, $9d, $77, $86, $2d, $9d, $9f
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d, $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d, $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1d
	.word @song0ref3524
	.byte $ff, $1d
	.word @song0ref3524
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d, $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1d
	.word @song0ref3524
	.byte $ff, $1d
	.word @song0ref3524
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d, $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
@song0ref3661:
	.byte $2d, $9d, $7a, $88, $29, $9d, $77, $86, $2d, $9d, $2d, $9d, $2d, $9d, $7a, $88, $29, $9d, $77, $86, $2d, $9d, $75, $84
	.byte $28, $85, $73, $87, $72, $87, $71, $87, $77, $86
	.byte $ff, $13
	.word @song0ref3661
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $13
	.word @song0ref3661
	.byte $77, $86
	.byte $ff, $13
	.word @song0ref3661
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d, $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d
	.byte $ff, $1e
	.word @song0ref3521
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d, $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1c
	.word @song0ref3524
	.byte $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1c
	.word @song0ref3524
	.byte $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1c
	.word @song0ref3524
	.byte $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1c
	.word @song0ref3524
	.byte $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $13
	.word @song0ref3661
	.byte $77, $86
	.byte $ff, $13
	.word @song0ref3661
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $13
	.word @song0ref3661
	.byte $77, $86
	.byte $ff, $13
	.word @song0ref3661
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1d
	.word @song0ref3524
	.byte $ff, $1d
	.word @song0ref3524
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d, $75, $84, $28, $85, $73, $87, $72, $87, $71, $87
	.byte $ff, $1d
	.word @song0ref3522
	.byte $ff, $1d
	.word @song0ref3524
	.byte $ff, $1d
	.word @song0ref3524
	.byte $ff, $1a
	.word @song0ref3524
	.byte $29, $8d, $29, $8d, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $ff, $14
	.word @song0ref1775
	.byte $f7, $f7, $f7, $f7, $9f, $f7, $f7, $f7, $f7, $9f, $fd
	.word @song0ch4loop
@song1ch0:
	.byte $6a, .lobyte(@tempo_env_4_mid), .hibyte(@tempo_env_4_mid), $79, $92, $39, $8d, $36, $8d, $34, $8d, $32, $8d, $6a, .lobyte(@tempo_env_4_3_3_3_mid)
	.byte .hibyte(@tempo_env_4_3_3_3_mid), $80, $12, $a5, $12, $a3, $12, $97, $15, $a5, $15, $a3, $15, $97, $17, $a5, $19, $a3
	.byte $1c, $97, $1e, $e5, $6a, .lobyte(@tempo_env_4_mid), .hibyte(@tempo_env_4_mid), $a9, $00, $9b
@song1ch0loop:
	.byte $00, $fd
	.word @song1ch0loop
@song1ch1:
	.byte $bf, $99, $7a, $8c, $2a, $97, $2c, $97, $2f, $97, $33, $a5, $31, $a3, $33, $97, $34, $a5, $33, $a3, $34, $97, $34, $85
	.byte $36, $8f, $63, .lobyte(@env28), .hibyte(@env28), $cd, $a9, $00, $9b
@song1ch1loop:
	.byte $00, $fd
	.word @song1ch1loop
@song1ch2:
	.byte $92, $2c, $8d, $2c, $8d, $2c, $8d, $2c, $8d, $2c, $b1, $2c, $b1, $2c, $b1, $2c, $b1, $2c, $b1, $2c, $b1, $2c, $b1, $2c
	.byte $8b, $2c, $89, $2c, $8b, $2c, $89, $a9, $00, $9b
@song1ch2loop:
	.byte $00, $fd
	.word @song1ch2loop
@song1ch3:
	.byte $7a, $88, $29, $8d, $29, $8d, $29, $8d, $29, $8d, $74, $86, $2e, $8b, $73, $2e, $89, $74, $2e, $8b, $71
@song1ref147:
	.byte $2e, $89, $7a, $88, $29, $97, $74, $86, $2e, $8b, $73, $2e, $89, $74, $2e, $8b, $71, $2e, $89, $74, $2e, $8b, $73
	.byte $ff, $0e
	.word @song1ref147
	.byte $73
	.byte $ff, $0e
	.word @song1ref147
	.byte $73, $2e, $89, $7a, $88, $29, $8b, $29, $89, $29, $8b, $29, $89, $b5, $00, $8f
@song1ch3loop:
	.byte $00, $fd
	.word @song1ch3loop
@song1ch4:
	.byte $bf, $f7, $f7, $f7, $b7, $c7
@song1ch4loop:
	.byte $00, $fd
	.word @song1ch4loop
@song2ch0:
	.byte $7a, $8e
@song2ref3:
	.byte $19
@song2ref4:
	.byte $ad, $79, $af, $78, $af, $77, $af, $76, $af, $75, $af, $74, $af, $73, $af, $7a
	.byte $ff, $08
	.word @song2ref3
	.byte $73, $97, $00, $95
@song2ch0loop:
	.byte $00, $fd
	.word @song2ch0loop
@song2ch1:
	.byte $7a, $8e, $14
	.byte $ff, $08
	.word @song2ref4
	.byte $7a, $1e, $ad, $79, $af, $78, $af, $77, $af, $76, $af, $75, $af, $74, $af, $73, $97, $00, $95
@song2ch1loop:
	.byte $00, $fd
	.word @song2ch1loop
@song2ch2:
	.byte $82, $3d, $ad, $3b, $ad, $39, $ad, $38, $ad, $36, $ad, $32, $c5, $34, $c5, $36, $f7, $c5, $00, $f7, $c5
@song2ch2loop:
	.byte $00, $fd
	.word @song2ch2loop
@song2ch3:
	.byte $f7, $f7, $f7, $f7, $f7, $f7, $af
@song2ch3loop:
	.byte $00, $fd
	.word @song2ch3loop
@song2ch4:
	.byte $f7, $f7, $f7, $f7, $f7, $f7, $af
@song2ch4loop:
	.byte $00, $fd
	.word @song2ch4loop
