;this file for FamiStudio Sound Engine generated by FamiStudio

; Info: Header size : 33 bytes.
; Info: Instruments size : 420 bytes.
; Info: Tempo envelopes size : 9 bytes.
; Info: Song 'Get Psyched' size: 4988 bytes.
; Info: Song 'Metal Heads' size: 2085 bytes.
; Info: Total assembly file size: 7535 bytes.
; Info: Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Info: Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Info: Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Info: Slide notes are used on the noise channel, you must set FAMISTUDIO_USE_NOISE_SLIDE_NOTES = 1.
; Info: Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Info: Arpeggios are used, you must set FAMISTUDIO_USE_ARPEGGIO = 1.
; Info: Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.

@music_data:
	.byte 2
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env_4_3_mid), .hibyte(@tempo_env_4_3_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4
	.byte .lobyte(@tempo_env_4_3_mid), .hibyte(@tempo_env_4_3_mid), 0, 0

@instruments:
	.word @env23,@env0,@env16,@env10
	.word @env25,@env6,@env12,@env21
	.word @env3,@env0,@env11,@env10
	.word @env3,@env0,@env16,@env10
	.word @env13,@env0,@env11,@env10
	.word @env4,@env2,@env11,@env14
	.word @env15,@env26,@env17,@env10
	.word @env15,@env26,@env11,@env10
	.word @env20,@env26,@env7,@env10
	.word @env3,@env26,@env7,@env10
	.word @env3,@env0,@env1,@env10
	.word @env9,@env0,@env11,@env10
	.word @env24,@env19,@env12,@env10

@samples:
	; .byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$36,$0f,$40	;1 (bark)
	; .byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$22,$0f,$40	;2 (sd1)
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c2,$c0,$00,$01
@env2:
	.byte $d0,$ae,$bc,$c2,$00,$03
@env3:
	.byte $04,$cf,$7f,$00,$01
@env4:
	.byte $00,$cd,$ca,$c8,$c6,$c4,$02,$c3,$02,$c2,$c2,$c1,$c0,$00,$0c
@env5:
	.byte $c0,$c4,$c7,$00,$00
@env6:
	.byte $cd,$c0,$00,$01
@env7:
	.byte $c0,$c0,$c1,$c1,$c2,$c2,$c1,$c1,$00,$00
@env8:
	.byte $c0,$cc,$cc,$00,$00
@env9:
	.byte $00,$cf,$03,$ce,$04,$cd,$cd,$cc,$02,$cb,$02,$ca,$02,$c9,$02,$c8,$03,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$03,$c0,$00,$1e
@env10:
	.byte $00,$c0,$7f,$00,$01
@env11:
	.byte $7f,$00,$00
@env12:
	.byte $c2,$7f,$00,$00
@env13:
	.byte $00,$ce,$cc,$c8,$c7,$c4,$c0,$00,$06
@env14:
	.byte $00,$c8,$c6,$c5,$c2,$be,$ba,$b7,$95,$00,$08
@env15:
	.byte $00,$ce,$ce,$cd,$cd,$cc,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c6,$c6,$c5,$c3,$c0,$00,$12
@env16:
	.byte $c1,$7f,$00,$00
@env17:
	.byte $c0,$c2,$00,$01
@env18:
	.byte $c0,$c0,$cc,$00,$00
@env19:
	.byte $c7,$c1,$bb,$b8,$b3,$af,$aa,$a6,$a3,$00,$08
@env20:
	.byte $00,$cf,$ce,$03,$cd,$04,$cc,$05,$cb,$02,$ca,$02,$c9,$c9,$c8,$c8,$c7,$03,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$00,$18
@env21:
	.byte $00,$c3,$c0,$00,$02
@env22:
	.byte $c0,$c3,$c7,$00,$00
@env23:
	.byte $00,$cf,$cf,$cd,$cd,$cc,$cc,$cb,$ca,$03,$c9,$c9,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$02,$c3,$c3,$c2,$00,$17
@env24:
	.byte $00,$cf,$ce,$ce,$cd,$cd,$cc,$cb,$cb,$ca,$02,$c9,$c9,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$c2,$c0,$00,$15
@env25:
	.byte $00,$cf,$03,$ce,$cd,$cd,$cc,$cc,$cb,$ca,$c9,$c7,$c6,$c6,$c5,$c5,$c4,$00,$10
@env26:
	.byte $cc,$c0,$00,$01
@env27:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01
@env28:
	.byte $00,$c0,$bc,$ba,$bb,$be,$c2,$c5,$c6,$c4,$00,$01
@env29:
	.byte $00,$c0,$bf,$be,$be,$bf,$c1,$c2,$c2,$c1,$00,$01
@tempo_env_4_3_mid:
	.byte $02,$06,$05,$06,$03,$06,$06,$03,$80
@song0ch0:
@song0ch0loop:
	.byte $66, $6a, .lobyte(@tempo_env_4_3_mid), .hibyte(@tempo_env_4_3_mid), $00, $f7, $f7, $f7, $d5, $6b, $00, $f7, $f7, $f7
	.byte $d5, $6b, $00, $f7, $f7, $f7, $d5, $6b, $00, $f7, $f7, $f7, $d5, $6b, $78, $69, $02, $84
@song0ref34:
	.byte $28, $99, $77, $63, .lobyte(@env27), .hibyte(@env27), $9b, $76, $9b, $78, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $61, $f4, $28, $2a, $8b, $62, $2a, $8b, $77, $9b, $76, $9b, $75, $63, .lobyte(@env28), .hibyte(@env28), $9b, $74, $9b
	.byte $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f7, $2a, $2b, $85, $62, $2b, $91, $77, $63, .lobyte(@env27)
	.byte .hibyte(@env27), $9b, $76, $9b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $06, $2b, $2a, $8b, $62, $2a
	.byte $8b, $76, $9b, $77, $9b, $78, $63, .lobyte(@env29), .hibyte(@env29), $9b, $62, $61, $1b, $2a, $22, $99, $6b, $69, $02
	.byte $28, $99, $77, $63, .lobyte(@env27), .hibyte(@env27), $9b, $76, $9b, $78, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $61, $f4, $28, $2a, $8b, $62, $2a, $8b, $77, $9b, $76, $9b, $75, $63, .lobyte(@env28), .hibyte(@env28), $9b, $74, $9b
	.byte $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $0a, $2a, $26, $99, $77, $63, .lobyte(@env27), .hibyte(@env27)
	.byte $87, $62, $26, $91, $76, $9b, $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $07, $26, $25, $8b, $62, $25, $8b
	.byte $77, $9b, $76, $9b, $63, .lobyte(@env29), .hibyte(@env29), $9b, $77, $62, $61, $1a, $25, $1f, $99, $6b, $78, $69, $02
	.byte $ff, $27
	.word @song0ref34
	.byte $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $ef, $2a, $32, $99, $77, $63, .lobyte(@env27), .hibyte(@env27)
	.byte $62, $32, $99, $76, $9b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f9, $32, $34, $8b, $62, $34, $8b, $76
	.byte $9b, $77, $9b, $78, $63, .lobyte(@env29), .hibyte(@env29), $9b, $9b, $6b, $69, $02
	.byte $ff, $36
	.word @song0ref34
	.byte $6b, $78, $69, $02
	.byte $ff, $27
	.word @song0ref34
@song0ref261:
	.byte $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $ef, $2a, $32, $99, $77, $63, .lobyte(@env27), .hibyte(@env27)
	.byte $62, $32, $99, $76, $9b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f9, $32, $34, $8b, $62, $34, $8b, $95
	.byte $00, $83, $74, $63, .lobyte(@env10), .hibyte(@env10), $64, $34, $93, $00, $83, $34, $85, $00, $83, $34, $85, $00, $83
	.byte $34, $85, $00, $83, $34, $85, $00, $83, $6b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64, $8c
@song0ref328:
	.byte $34, $8b, $40, $8b, $76, $2f, $8b, $3b, $8b, $77, $2b, $8b, $37, $8b, $78, $2f, $8b, $3b, $8b, $77, $2d, $8b, $39, $8b
	.byte $76, $37, $8b, $36, $8b, $75, $34, $8b, $37, $8b, $74, $36, $8b, $34, $8b, $75
	.byte $ff, $1c
	.word @song0ref328
	.byte $74, $39, $8b, $3b, $8b, $6b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $20
	.word @song0ref328
	.byte $75
	.byte $ff, $1c
	.word @song0ref328
	.byte $74, $39, $8b, $3b, $8b, $6b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $20
	.word @song0ref328
	.byte $75
	.byte $ff, $1c
	.word @song0ref328
	.byte $74, $39, $8b, $3b, $8b, $6b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $20
	.word @song0ref328
	.byte $75, $34, $8b, $32, $8b, $76, $30, $8b, $2f, $8b, $75, $28, $8b, $26, $8b, $76, $24, $8b, $77, $23, $8b, $69, $02, $84
	.byte $1e, $99, $63, .lobyte(@env29), .hibyte(@env29), $9b, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $00, $61, $ee
	.byte $1e, $1f, $85, $69, $00, $61, $e9, $1f, $20, $83, $69, $01, $61, $f0, $20, $21, $85, $69, $01, $61, $eb, $21, $22, $83
	.byte $69, $02, $61, $f2, $22, $23, $85, $69, $02, $61, $f2, $23, $24, $83, $69, $01, $61, $ef, $24, $25, $85, $69, $01, $61
	.byte $f4, $25, $26, $83
@song0ref511:
	.byte $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $01, $34, $85, $77, $61, $f6, $34, $36, $83, $63, .lobyte(@env27)
	.byte .hibyte(@env27), $62, $36, $8b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $34, $85, $77, $61, $f6
	.byte $34, $36, $83, $63, .lobyte(@env27), .hibyte(@env27), $62, $36, $8b, $9b, $76, $9b, $9b, $75, $9b, $9b, $74, $62, $61
	.byte $1d, $36, $2b, $93, $63, .lobyte(@env10), .hibyte(@env10), $64, $62, $2b, $83, $77, $65, .lobyte(@env18), .hibyte(@env18)
	.byte $69, $00, $36, $85, $72, $67, $36, $83, $77, $67, $69, $01, $34, $85, $72, $67, $34, $83, $77, $67, $69, $02, $32, $85
	.byte $72, $67, $32, $83, $77, $67, $69, $01, $31, $85, $72, $67, $31, $83, $77, $67, $69, $00, $2f, $85, $72, $67, $2f, $83
	.byte $77, $67, $69, $01, $2d, $85, $72, $67, $2d, $83, $77, $67, $69, $02, $2b, $85, $72, $67, $2b, $83, $77, $67, $69, $00
	.byte $2a, $85, $72, $67, $2a, $83, $77, $67, $69, $01, $28, $99, $65, .lobyte(@env8), .hibyte(@env8), $69, $02, $28, $99
	.byte $65, .lobyte(@env0), .hibyte(@env0), $66, $62, $61, $1d, $28, $1b, $b5, $6b, $69, $01, $1e, $b5, $69, $00, $61, $ee
	.byte $1e, $1f, $85, $69, $01, $61, $d4, $1f, $21, $83, $69, $02, $61, $f0, $21, $22, $85, $69, $01, $61, $ed, $22, $23, $83
	.byte $69, $00, $61, $f2, $23, $24, $85, $69, $01, $61, $f3, $24, $25, $83, $69, $02, $61, $f0, $25, $26, $85, $69, $01, $61
	.byte $f4, $26, $27, $83, $69, $00, $61, $f2, $27, $28
@song0ref747:
	.byte $85, $62, $28, $91, $63, .lobyte(@env28), .hibyte(@env28), $b7, $62, $61, $1a, $28, $21, $99, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $69, $00, $1f, $b5, $69, $00, $22, $85, $69, $01, $23, $83, $69, $02, $24, $85, $69, $01, $25
	.byte $83, $69, $00, $26, $85, $69, $01, $27, $83, $69, $02, $28, $85, $69, $01, $29, $83, $69, $02, $2a, $99, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $b7, $62, $61, $1b, $2a, $22, $99
	.byte $ff, $41
	.word @song0ref511
	.byte $69, $02, $61, $e2, $21, $23, $85, $69, $01, $61, $dd, $23, $25, $83, $69, $00, $61, $f4, $25, $26, $85, $69, $01, $61
	.byte $f4, $26, $27, $83, $69, $02, $61, $f2, $27, $28, $85, $69, $01, $61, $f5, $28, $29, $83, $69, $00, $61, $f3, $29, $2a
@song0ref866:
	.byte $85, $62, $2a, $91, $63, .lobyte(@env28), .hibyte(@env28), $d3, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $00
	.byte $28, $b5, $69, $00, $25, $85, $69, $01, $26, $83, $69, $02, $27, $85, $69, $01, $28, $83, $69, $00, $29, $85, $69, $01
	.byte $2a, $83, $69, $02, $2b, $85, $69, $01, $2c, $83, $69, $02, $2d, $99, $63, .lobyte(@env28), .hibyte(@env28), $9b, $63
	.byte .lobyte(@env10), .hibyte(@env10), $64, $69, $00, $2d, $85, $73, $85, $77, $69, $01, $2d, $85, $73, $85, $77, $65, .lobyte(@env18)
	.byte .hibyte(@env18), $69, $02, $2d, $85, $73, $85, $77, $65, .lobyte(@env8), .hibyte(@env8), $2d, $85, $73, $85, $6b, $00
	.byte $f7, $f7, $f7, $d5, $6b, $00, $f7, $f7, $f7, $d5, $6b, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env0)
	.byte .hibyte(@env0), $66, $69, $02, $1c, $99, $76, $63, .lobyte(@env27), .hibyte(@env27), $9b, $75, $9b, $77, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $61, $f4, $1c, $1e, $99, $76, $62, $1e, $99, $75, $9b, $74, $63, .lobyte(@env28), .hibyte(@env28)
	.byte $9b, $73, $f7, $af, $77, $69, $02, $1c, $8b, $72, $69, $02, $1c, $8b, $77, $69, $00, $1c, $8b, $72, $69, $00, $1c, $8b
	.byte $77, $69, $01, $1c, $8b, $72, $69, $01, $1c, $8b, $6b, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $1c
	.byte $99, $76, $63, .lobyte(@env27), .hibyte(@env27), $9b, $75, $9b, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $61
	.byte $0a, $1c, $1a, $99, $76, $87, $62, $1a, $91, $75, $9b, $74, $63, .lobyte(@env28), .hibyte(@env28), $9b, $73, $f7, $af
	.byte $77, $69, $02, $1a, $8b, $72, $69, $02, $1a, $8b, $77, $69, $00, $1c, $8b, $72, $69, $00, $1c, $8b, $77, $69, $01, $1a
	.byte $8b, $72, $69, $01, $1a, $8b, $6b, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $1f, $99, $76, $63, .lobyte(@env27)
	.byte .hibyte(@env27), $9b, $75, $9b, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f6, $1f, $21, $99, $76, $62
	.byte $21, $99, $75, $9b, $74, $63, .lobyte(@env28), .hibyte(@env28), $9b, $73, $f7, $af, $77, $69, $02, $1f, $8b, $72, $69
	.byte $02, $1f, $8b, $77, $69, $00, $1f, $8b, $72, $69, $00, $1f, $8b, $77, $69, $01, $1f, $8b, $72, $69, $01, $1f, $8b, $6b
	.byte $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $21, $8b, $73, $69, $02, $21, $8b, $78, $69, $02, $21, $8b
	.byte $73, $69, $02, $21, $a1, $1f, $83, $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $61, $f6, $1f, $20, $8b
	.byte $73, $69, $02, $21, $8b, $78, $69, $02, $21, $8b, $73, $69, $02, $21, $a7, $78, $69, $02, $61, $1b, $21, $18, $b5, $63
	.byte .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $21, $8b, $73, $69, $02, $21, $8b, $78, $69, $02, $21, $8b, $73, $69
	.byte $02, $21, $a1, $1f, $83, $78, $65, .lobyte(@env18), .hibyte(@env18), $69, $02, $61, $f6, $1f, $20, $8b, $73, $67, $69
	.byte $02, $21, $8b, $78, $67, $69, $02, $21, $8b, $73, $67, $69, $02, $21, $a7, $79, $67, $80, $24, $99, $67, $24, $99, $6b
	.byte $78, $65, .lobyte(@env0), .hibyte(@env0), $66, $82
@song0ref1318:
	.byte $0e, $99, $1a, $b5, $10, $99, $1c, $b5, $11, $99, $1d, $99, $0e, $99, $1a, $b5, $10, $99, $1c, $b5, $0c, $99, $18, $99
	.byte $6b
	.byte $ff, $18
	.word @song0ref1318
	.byte $6b
	.byte $ff, $18
	.word @song0ref1318
	.byte $6b
	.byte $ff, $18
	.word @song0ref1318
	.byte $6b
	.byte $ff, $18
	.word @song0ref1318
	.byte $6b
	.byte $ff, $18
	.word @song0ref1318
	.byte $6b
	.byte $ff, $18
	.word @song0ref1318
	.byte $6b, $0e, $99, $1a, $b5, $10, $99, $1c, $b5, $11, $99, $1d, $99, $0e, $99, $1a, $b5, $10, $99, $1c, $b5, $73, $8c, $34
	.byte $85, $00, $83, $40, $85, $00, $83, $74, $2f, $85, $00, $83, $3b, $85, $00, $83, $6b, $75, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64
	.byte $ff, $20
	.word @song0ref328
	.byte $75
	.byte $ff, $1c
	.word @song0ref328
	.byte $74, $39, $8b, $3b, $8b, $6b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $20
	.word @song0ref328
	.byte $75
	.byte $ff, $1c
	.word @song0ref328
	.byte $74, $39, $8b, $3b, $8b, $6b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $20
	.word @song0ref328
	.byte $75
	.byte $ff, $1c
	.word @song0ref328
	.byte $74, $39, $8b, $3b, $8b, $6b, $75, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $20
	.word @song0ref328
	.byte $75, $34, $8b, $32, $8b, $76, $30, $8b, $2f, $8b, $75, $28, $8b, $26, $8b, $76, $24, $8b, $77, $23, $8b, $63, .lobyte(@env29)
	.byte .hibyte(@env29), $69, $02, $84, $2a, $99, $62, $61, $1b, $2a, $22, $99, $75, $65, .lobyte(@env18), .hibyte(@env18)
	.byte $69, $02, $2d, $8b, $00, $8b, $67, $69, $02, $2f, $8b, $00, $8b, $6b, $78, $65, .lobyte(@env0), .hibyte(@env0), $66
	.byte $69, $02
	.byte $ff, $36
	.word @song0ref34
	.byte $6b, $78, $69, $02
	.byte $ff, $27
	.word @song0ref34
	.byte $ff, $20
	.word @song0ref261
	.byte $6b, $78, $69, $02
	.byte $ff, $36
	.word @song0ref34
	.byte $6b, $78, $69, $02
	.byte $ff, $27
	.word @song0ref34
	.byte $ff, $20
	.word @song0ref261
	.byte $6b, $82
@song0ref1561:
	.byte $61, $19, $10, $0f, $8b, $00, $a7, $61, $19, $10, $0f, $8b, $00, $8b, $61, $19, $10, $0f, $8b, $00, $a7, $61, $19, $10
	.byte $0f, $8b, $00, $8b, $61, $19, $10, $0f, $8b, $00, $a7, $61, $19, $10, $0f, $8b, $00, $a7, $61, $19, $10, $0f, $8b, $00
	.byte $8b, $61, $19, $10, $0f, $8b, $00, $a7, $61, $19, $10, $0f, $8b, $00, $8b, $61, $11, $17, $16, $8b, $00, $a7, $6b
	.byte $ff, $28
	.word @song0ref1561
	.byte $6b
	.byte $ff, $28
	.word @song0ref1561
	.byte $6b
	.byte $ff, $28
	.word @song0ref1561
	.byte $6b
	.byte $ff, $28
	.word @song0ref1561
	.byte $6b
	.byte $ff, $28
	.word @song0ref1561
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $66, $00, $f7, $f7, $f7, $d5, $00, $f7, $f7, $f7, $d5, $00, $f7, $f7, $f7, $d5, $00, $f7, $f7, $f7, $d5, $73, $9b, $68
	.byte $fe
@song0ref1680:
	.byte $69, $02, $84
@song0ref1683:
	.byte $28, $99, $72, $63, .lobyte(@env27), .hibyte(@env27), $9b, $74, $9b, $73, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $61, $f4, $28, $2a, $8b, $62, $2a, $8b, $72, $9b, $71, $9b, $63, .lobyte(@env28), .hibyte(@env28), $9b, $74, $9b
	.byte $73, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f7, $2a, $2b, $85, $62, $2b, $91, $72, $63, .lobyte(@env27)
	.byte .hibyte(@env27), $9b, $71, $9b, $72, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $06, $2b, $2a, $8b
	.byte $62, $2a, $8b, $73, $9b, $74, $9b, $63, .lobyte(@env29), .hibyte(@env29), $9b, $62, $61, $1b, $2a, $22, $99, $73, $68
	.byte $fe, $69, $02, $28, $99, $72, $63, .lobyte(@env27), .hibyte(@env27), $9b, $71, $b7, $68, $fe, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $61, $f4, $28, $2a, $8b, $62, $2a, $8b, $9b, $63, .lobyte(@env28), .hibyte(@env28), $9b, $72
	.byte $9b, $73, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $0a, $2a, $26, $99, $72, $63, .lobyte(@env27)
	.byte .hibyte(@env27), $87, $62, $26, $91, $71, $9b, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $07, $26
	.byte $25, $8b, $62, $25, $8b, $9b, $9b, $72, $63, .lobyte(@env29), .hibyte(@env29), $9b, $73, $9b, $68, $fe, $69, $02
	.byte $ff, $19
	.word @song0ref1683
@song0ref1855:
	.byte $73, $62, $61, $1a, $25, $1f, $99, $68, $fe, $69, $02, $28, $99, $72, $63, .lobyte(@env27), .hibyte(@env27), $9b, $71
	.byte $9b, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f4, $28, $2a, $8b, $62, $2a, $8b, $9b, $9b, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $9b, $72, $9b, $73, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $ef, $2a, $32, $99
	.byte $72, $63, .lobyte(@env27), .hibyte(@env27), $62, $32, $99, $71, $9b, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $61, $f9, $32, $34, $8b, $62, $34, $8b, $9b, $9b, $72
@song0ref1935:
	.byte $63, .lobyte(@env29), .hibyte(@env29), $9b, $74, $62, $61, $1d, $34, $27, $99, $68, $fe, $69, $02, $28, $99, $73, $63
	.byte .lobyte(@env27), .hibyte(@env27), $9b, $78, $68, $00, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env22)
	.byte .hibyte(@env22), $80, $34, $85, $77, $85, $76, $87, $75, $85, $74, $87, $73, $85, $72, $87, $71, $85, $68, $fe, $63
	.byte .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env0), .hibyte(@env0), $66, $84, $2a, $99, $72, $9b, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $9b, $73, $9b, $74, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f7, $2a, $2b, $85
	.byte $62, $2b, $91, $73, $63, .lobyte(@env27), .hibyte(@env27), $9b, $78, $68, $00, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $65, .lobyte(@env5), .hibyte(@env5), $80, $32, $85, $77, $85, $76, $87, $75, $85, $74, $87, $73, $85, $72, $87
	.byte $71, $85, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env0), .hibyte(@env0), $66, $84, $2a
	.byte $99, $72, $9b, $73, $63, .lobyte(@env29), .hibyte(@env29), $9b, $62, $61, $1b, $2a, $22, $99, $74, $68, $fe, $69, $02
	.byte $28, $99, $73, $63, .lobyte(@env27), .hibyte(@env27), $9b, $78, $68, $00, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $65, .lobyte(@env22), .hibyte(@env22), $80, $34, $85, $77, $85, $76, $87, $75, $85, $74, $87, $73, $85, $72, $87, $71
	.byte $85, $73, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env0), .hibyte(@env0), $66, $84, $2a
	.byte $99, $72, $9b, $63, .lobyte(@env28), .hibyte(@env28), $9b, $73, $9b, $74, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $61, $0a, $2a, $26, $99, $73, $63, .lobyte(@env27), .hibyte(@env27), $87, $62, $26, $91, $78, $68, $00, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $65, .lobyte(@env5), .hibyte(@env5), $80, $32, $85, $77, $85, $76, $87, $75, $85, $74, $87, $73
	.byte $85, $72, $87, $71, $85, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env0), .hibyte(@env0)
	.byte $66, $84, $25, $99, $72, $9b, $73
	.byte $ff, $26
	.word @song0ref1935
@song0ref2205:
	.byte $75, $62, $61, $1a, $25, $1f, $99, $68, $fe, $69, $02, $28, $99, $74, $63, .lobyte(@env27), .hibyte(@env27), $9b, $79
	.byte $68, $00, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env22), .hibyte(@env22), $80, $34, $85, $78, $85
	.byte $77, $87, $76, $85, $75, $87, $74, $85, $73, $87, $72, $85, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $65
	.byte .lobyte(@env0), .hibyte(@env0), $66, $84, $2a, $99, $73, $9b, $63, .lobyte(@env28), .hibyte(@env28), $9b, $74, $9b
	.byte $75, $68, $fe, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $ef, $2a, $32, $99, $74, $62, $32, $99, $79, $68, $00
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env5), .hibyte(@env5), $80, $32, $85, $78, $85, $77, $87
	.byte $76, $85, $75, $87, $74, $85, $73, $87, $72, $85, $00, $99, $75, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env0)
	.byte .hibyte(@env0), $66, $84, $2f, $85, $00, $83, $76, $2f, $85, $00, $83, $77, $2f, $85, $00, $83, $2f, $85, $00, $83
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $00, $93, $71
@song0ref2351:
	.byte $8c
@song0ref2352:
	.byte $34, $8b, $40, $8b, $72, $2f, $8b, $3b, $8b, $73, $2b, $83, $79, $68, $00, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $65, .lobyte(@env22), .hibyte(@env22), $80, $34, $85, $78, $85, $77, $87, $76, $85, $75, $87, $74, $85, $73, $87, $72
	.byte $8d, $73, $65, .lobyte(@env0), .hibyte(@env0), $66, $8c, $39, $8b, $72, $37, $8b, $36, $8b, $71, $34, $8b, $37, $8b
	.byte $36, $8b, $34, $8b, $34, $8b, $40, $8b, $72, $2f, $8b, $3b, $8b, $73, $2b, $83, $79, $68, $00, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $65, .lobyte(@env5), .hibyte(@env5), $80, $32, $85, $78, $85, $77, $87, $76, $85, $75, $87, $74
	.byte $85, $73, $87, $72, $8d, $73, $65, .lobyte(@env0), .hibyte(@env0), $66, $8c, $39, $8b, $72, $37, $8b, $36, $8b, $71
	.byte $34, $8b, $37, $8b, $39, $83, $87, $3b, $8b
	.byte $ff, $43
	.word @song0ref2352
	.byte $ff, $43
	.word @song0ref2352
	.byte $ff, $33
	.word @song0ref2352
	.byte $72, $85, $71, $87, $70, $85, $00, $c3, $9b, $72, $68, $fe, $65, .lobyte(@env0), .hibyte(@env0), $66, $69, $01, $84
@song0ref2503:
	.byte $34, $85, $73, $68, $fe, $61, $f6, $34, $36, $83, $63, .lobyte(@env27), .hibyte(@env27), $62, $36, $8b, $72, $68, $fe
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $34, $85, $73, $68, $fe, $61, $f2, $34, $36, $83, $63, .lobyte(@env27)
	.byte .hibyte(@env27), $62, $36, $8b, $9b, $72, $9b, $9b, $71, $9b, $9b, $70, $62, $61, $1a, $36, $2b, $93, $63, .lobyte(@env10)
	.byte .hibyte(@env10), $64, $62, $2b, $83, $73, $68, $fe, $65, .lobyte(@env18), .hibyte(@env18), $69, $00, $36, $85, $70
	.byte $68, $fe, $67, $36, $83, $73, $68, $fe, $67, $69, $01, $34, $85, $70, $68, $fe, $67, $34, $83, $73, $68, $fe, $67, $69
	.byte $02, $32, $85, $70, $68, $fe, $67, $32, $83, $73, $68, $fe, $67, $69, $01, $31, $85, $70, $68, $fe, $67, $31, $83, $73
	.byte $68, $fe, $67, $69, $00, $2f, $85, $70, $68, $fe, $67, $2f, $83, $73, $68, $fe, $67, $69, $01, $2d, $85, $70, $68, $fe
	.byte $67, $2d, $83, $73, $68, $fe, $67, $69, $02, $2b, $85, $70, $68, $fe, $67, $2b, $83, $73, $68, $fe, $67, $69, $00, $2a
	.byte $85, $70, $68, $fe, $67, $2a, $83, $72, $68, $fe, $67, $69, $01, $28, $99, $68, $fe, $65, .lobyte(@env8), .hibyte(@env8)
	.byte $69, $02, $28, $99, $65, .lobyte(@env0), .hibyte(@env0), $66, $62, $61, $1c, $28, $1b, $99, $9b, $69, $01, $1e, $b5
	.byte $69, $00, $61, $ee, $1e, $1f, $85, $69, $01, $61, $df, $1f, $21, $83, $69, $02, $61, $eb, $21, $22, $85, $69, $01, $61
	.byte $f2, $22, $23, $83, $69, $00, $61, $ee, $23, $24, $85, $69, $01, $61, $f3, $24, $25, $83, $69, $02, $61, $f0, $25, $26
	.byte $85, $69, $01, $61, $f0, $26, $27, $83, $69, $00, $61, $f5, $27, $28
	.byte $ff, $1b
	.word @song0ref747
	.byte $9b, $68, $fe, $69, $01
	.byte $ff, $42
	.word @song0ref2503
	.byte $69, $02, $61, $d8, $21, $23, $85, $69, $01, $61, $e6, $23, $25, $83, $69, $00, $61, $f0, $25, $26, $85, $69, $01, $61
	.byte $f4, $26, $27, $83, $69, $02, $61, $f2, $27, $28, $85, $69, $01, $61, $f2, $28, $29, $83, $69, $00, $61, $f6, $29, $2a
	.byte $ff, $19
	.word @song0ref866
	.byte $73, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $00, $2d, $85, $70, $85, $73, $69, $01, $2d, $85, $70, $85, $73
	.byte $65, .lobyte(@env18), .hibyte(@env18), $69, $02, $2d, $85, $70, $85, $73, $65, .lobyte(@env8), .hibyte(@env8), $2d
	.byte $85, $70, $85, $00, $f7, $f7, $f7, $b9, $00, $f7, $f7, $f7, $d5, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $65
	.byte .lobyte(@env0), .hibyte(@env0), $66, $69, $02, $23, $99, $76, $63, .lobyte(@env27), .hibyte(@env27), $9b, $75, $9b
	.byte $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f6, $23, $25, $93, $62, $25, $83, $76, $9b, $75, $9b, $74, $63
	.byte .lobyte(@env28), .hibyte(@env28), $9b, $73, $f7, $af, $77, $69, $02, $23, $8b, $72, $69, $02, $23, $8b, $77, $69, $00
	.byte $23, $8b, $72, $69, $00, $23, $8b, $77, $69, $01, $23, $8b, $72, $69, $01, $23, $8b, $77, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $69, $02, $23, $99, $76, $63, .lobyte(@env27), .hibyte(@env27), $9b, $75, $9b, $77, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $61, $0b, $23, $21, $93, $62, $21, $83, $76, $9b, $75, $9b, $74, $63, .lobyte(@env28), .hibyte(@env28), $9b, $73
	.byte $f7, $af, $77, $69, $02, $21, $8b, $72, $69, $02, $21, $8b, $77, $69, $00, $23, $8b, $72, $69, $00, $23, $8b, $77, $69
	.byte $01, $21, $8b, $72, $69, $01, $21, $8b, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $26, $99, $76, $63
	.byte .lobyte(@env27), .hibyte(@env27), $9b, $75, $9b, $77, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $f8, $26, $28
	.byte $93, $62, $28, $83, $76, $9b, $75, $9b, $74, $63, .lobyte(@env28), .hibyte(@env28), $9b, $73, $f7, $af, $77, $69, $02
	.byte $26, $8b, $72, $69, $02, $26, $8b, $77, $69, $00, $26, $8b, $72, $69, $00, $26, $8b, $77, $69, $01, $26, $8b, $72, $69
	.byte $01, $26, $8b, $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $28, $8b, $73, $69, $02, $28, $8b, $78, $69
	.byte $02, $28, $8b, $73, $69, $02, $28, $a1, $26, $83, $78, $69, $02, $61, $f9, $26, $27, $8b, $73, $69, $02, $28, $8b, $78
	.byte $69, $02, $28, $8b, $73, $69, $02, $28, $a7, $78, $69, $02, $61, $1d, $28, $1b, $b5, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $69, $02, $28, $8b, $73, $69, $02, $28, $8b, $78, $69, $02, $28, $8b, $73, $69, $02, $28, $a1, $26, $83, $78, $65
	.byte .lobyte(@env18), .hibyte(@env18), $69, $02, $61, $f9, $26, $27, $8b, $73, $67, $69, $02, $28, $8b, $78, $67, $69, $02
	.byte $28, $8b, $73, $67, $69, $02, $28, $a7, $79, $67, $80, $2b, $99, $67, $2b, $99, $b7, $78
@song0ref3219:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env22), .hibyte(@env22), $2b, $b5, $65, .lobyte(@env5), .hibyte(@env5)
	.byte $2d, $d1, $67, $2e, $d1, $65, .lobyte(@env22), .hibyte(@env22), $2b, $b5, $65, .lobyte(@env5), .hibyte(@env5), $2d
	.byte $d1, $67, $29, $99, $b7, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env22), .hibyte(@env22), $2b, $b5
	.byte $65, .lobyte(@env5), .hibyte(@env5), $2d, $d1, $67, $2e, $d1, $65, .lobyte(@env22), .hibyte(@env22), $2b, $b5, $65
	.byte .lobyte(@env5), .hibyte(@env5), $2d, $d1, $67, $30, $99, $b7
	.byte $ff, $1a
	.word @song0ref3219
	.byte $ff, $1a
	.word @song0ref3219
	.byte $ff, $19
	.word @song0ref3219
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $00, $93, $71, $65, .lobyte(@env0), .hibyte(@env0), $66
	.byte $ff, $43
	.word @song0ref2351
	.byte $ff, $43
	.word @song0ref2352
	.byte $ff, $43
	.word @song0ref2352
	.byte $ff, $33
	.word @song0ref2352
	.byte $72, $85, $71, $87, $70, $85, $00, $c3, $73, $9b, $68, $fe, $65, .lobyte(@env0), .hibyte(@env0), $66
	.byte $ff, $34
	.word @song0ref1680
	.byte $68, $fe, $69, $02
	.byte $ff, $19
	.word @song0ref1683
	.byte $ff, $63
	.word @song0ref1855
	.byte $73
	.byte $ff, $26
	.word @song0ref1935
	.byte $ff, $32
	.word @song0ref2205
	.byte $00, $f7, $f7, $f7, $d5, $00, $f7, $f7, $f7, $d5, $65, .lobyte(@env22), .hibyte(@env22)
@song0ref3362:
	.byte $69, $00, $28, $85, $76, $85, $75, $87, $74, $85, $73, $87, $72, $85, $77, $67, $69, $01, $28, $85, $74, $85, $77, $67
	.byte $69, $02, $34, $85, $76, $85, $75, $87, $74, $85, $77, $67, $69, $01, $28, $85, $76, $85, $75, $87, $74, $85, $77, $67
	.byte $69, $01, $1c, $85, $85, $76, $87, $85, $75, $87, $74, $85, $73, $87, $72, $85, $77, $67, $69, $00, $34, $85, $85, $76
	.byte $87, $85, $75, $87, $85, $74, $87, $85, $77, $67, $69, $01, $40, $99, $76, $9b, $75, $9b, $74, $9b, $73, $b7, $77, $67
	.byte $69, $00, $34, $85, $76, $85, $75, $87, $74, $85, $73, $87, $72, $85, $71, $87, $70, $85, $77, $67
	.byte $ff, $26
	.word @song0ref3362
	.byte $77, $67, $69, $01, $34, $99, $76, $9b, $75, $9b, $74, $9b, $73, $9b, $72, $9b, $71, $9b, $70, $9b, $77, $67
	.byte $ff, $35
	.word @song0ref3362
	.byte $77, $67
	.byte $ff, $26
	.word @song0ref3362
	.byte $77, $67, $69, $00, $28, $85, $76, $85, $75, $87, $74, $85, $73, $87, $72, $85, $77, $67, $69, $01, $28, $85, $74, $85
	.byte $77, $67, $69, $02, $34, $85, $76, $85, $75, $87, $74, $85, $77, $67, $69, $01, $28, $85, $76, $85, $75, $87, $74, $85
	.byte $77, $67, $69, $00, $34, $85, $76, $85, $75, $87, $74, $85, $77, $67, $69, $01, $28, $85, $85, $76, $87, $85, $75, $87
	.byte $85, $74, $87, $85, $73, $87, $85, $72, $87, $85, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref3597:
	.byte $98
@song0ref3598:
	.byte $2f, $b5, $2f, $8b, $00, $8b, $2f, $b5, $2f, $8b, $00, $8b, $2f, $8b, $00, $a7, $2f, $b5, $2f, $8b, $00, $8b, $2f, $b5
	.byte $2f, $8b, $00, $8b, $2f, $8b, $00, $a7
	.byte $ff, $20
	.word @song0ref3598
@song0ref3633:
	.byte $2f, $85, $84, $10, $91, $1c, $99, $98, $2f, $8b, $00, $8b, $2f, $85, $84, $12, $91, $1e, $99, $98, $2f, $8b, $00, $8b
	.byte $2f, $85, $84, $13, $91, $1f, $85, $1f, $91, $98, $2f, $85, $84, $10, $91, $1c, $99, $98, $2f, $8b, $00, $8b, $2f, $85
	.byte $84, $12, $91, $1e, $99, $98, $2f, $8b, $00, $8b, $2f, $85, $84, $0e, $91, $1a, $99, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $85, $84, $0e, $83, $98, $2f, $85, $84, $0e, $83, $98, $2f, $85, $84, $0e, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $85, $84, $0e, $83, $98, $2f, $85, $84, $0e, $83, $98, $2f, $85, $84, $0e
@song0ref3894:
	.byte $83
@song0ref3895:
	.byte $98, $2d, $85, $84, $0e, $91, $1a, $99, $98, $2d, $8b, $00, $8b, $2d, $85, $84, $10, $91, $1c, $99, $98, $2d, $8b, $00
	.byte $8b, $2d, $85, $84, $11, $91, $1d, $85, $1d, $91, $98, $2d, $85, $84, $0e, $91, $1a, $99, $98, $2d, $8b, $00, $8b, $2d
	.byte $85, $84, $10, $91, $1c, $99, $98, $2d, $8b, $00, $8b, $2d, $85, $84, $0c, $91, $18, $99
	.byte $ff, $33
	.word @song0ref3895
	.byte $83, $98, $2d, $85, $84, $0c, $83, $98, $2d, $85, $84, $0c, $83, $98, $2d, $85, $84, $0c
	.byte $ff, $37
	.word @song0ref3894
	.byte $ff, $36
	.word @song0ref3895
	.byte $ff, $36
	.word @song0ref3895
	.byte $ff, $36
	.word @song0ref3895
	.byte $ff, $36
	.word @song0ref3895
	.byte $ff, $36
	.word @song0ref3895
	.byte $ff, $36
	.word @song0ref3895
	.byte $ff, $33
	.word @song0ref3895
	.byte $83, $98, $2d, $85, $84, $0c, $83, $98, $2d, $85, $84, $0c, $83, $98, $2d, $85, $84, $0c, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83, $98
	.byte $ff, $36
	.word @song0ref3633
	.byte $98
	.byte $ff, $33
	.word @song0ref3633
	.byte $83, $98, $2f, $8b, $2f, $85, $84, $1a, $83, $98, $2f, $85, $84, $1a, $83
	.byte $ff, $20
	.word @song0ref3597
	.byte $ff, $20
	.word @song0ref3598
	.byte $ff, $20
	.word @song0ref3598
	.byte $ff, $20
	.word @song0ref3598
	.byte $ff, $20
	.word @song0ref3598
	.byte $ff, $20
	.word @song0ref3598
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref4170:
	.byte $75, $88, $2e
@song0ref4173:
	.byte $8b, $74, $2b, $8b, $75
@song0ref4178:
	.byte $2e, $8b, $74, $2e, $8b, $7a, $8a, $29, $99, $75, $88, $2e, $99, $2e, $8b, $73, $2e, $8b, $75, $2e, $8b, $73, $2e, $8b
	.byte $7a, $8a, $29, $99, $75, $88, $2e, $8b, $2e, $85, $73, $2e, $83, $75, $2e, $99
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
@song0ref4248:
	.byte $2e, $8b, $74, $2e, $8b, $7a, $8a, $29, $99, $75, $88, $2e, $99, $2e, $8b, $73, $2e, $8b, $75, $2e, $8b, $73, $2e, $8b
	.byte $7a, $8a, $29, $8b, $29, $8b, $29, $8b, $29, $8b
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
@song0ref4426:
	.byte $8b, $74, $2b, $8b, $86, $28, $99, $7a, $8a, $29, $99, $75, $88, $2e, $99, $86, $25, $99, $88, $2e, $8b, $73, $2e, $8b
	.byte $7a, $8a, $29, $99, $75, $86, $24, $99, $88, $2e, $8b, $74, $2b, $8b, $75, $86, $28, $99, $7a, $8a, $29, $99, $75, $88
	.byte $2e, $99, $86, $25, $99, $88, $2e, $8b, $73, $2e, $8b, $7a, $8a, $29, $99, $75, $86, $2b, $99, $77, $88, $2e, $8b, $76
	.byte $2b, $8b, $74, $86, $28, $99, $7a, $8a, $29, $99, $77, $88, $2e, $99, $75, $86, $25, $99, $77, $88, $2e, $8b, $75, $2e
	.byte $8b, $7a, $8a, $29, $99, $75, $86, $24, $99, $77, $88, $2e, $8b, $76, $2b, $8b, $74, $86, $28, $99, $7a, $8a, $29, $99
	.byte $77, $88, $2e, $99, $75, $86, $25, $99, $77, $88, $2e, $8b, $75, $2e, $8b, $7a, $8a, $29, $99, $75, $86, $2c, $99, $88
	.byte $2e
	.byte $ff, $27
	.word @song0ref4426
	.byte $88, $2e
	.byte $ff, $17
	.word @song0ref4426
	.byte $86, $28, $99, $7a, $8a, $29, $99, $75, $88, $2e, $99, $86, $25, $99, $88, $2e, $8b, $73, $2e, $8b, $7a, $8a, $29, $8b
	.byte $29, $8b, $29, $8b, $29, $8b
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4248
	.byte $ff, $1e
	.word @song0ref4170
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $19
	.word @song0ref4178
	.byte $ff, $1d
	.word @song0ref4173
	.byte $ff, $18
	.word @song0ref4178
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref4721:
	.byte $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7
	.byte $ff, $18
	.word @song0ref4721
	.byte $ff, $18
	.word @song0ref4721
	.byte $ff, $18
	.word @song0ref4721
	.byte $ff, $18
	.word @song0ref4721
	.byte $ff, $18
	.word @song0ref4721
	.byte $ff, $18
	.word @song0ref4721
	.byte $ff, $18
	.word @song0ref4721
	.byte $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $fd
	.word @song0ch4loop
@song1ch0:
@song1ref1:
	.byte $76
@song1ref2:
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $8e
@song1ref9:
	.byte $30, $8b, $3c, $8b, $77, $2b, $8b, $37, $8b, $78, $27, $8b, $33, $8b, $79, $2b, $8b, $37, $8b, $78, $69, $01, $29, $8b
	.byte $35, $8b, $77, $33, $8b, $32, $8b, $76, $30, $8b, $33, $8b, $75, $32, $8b, $30, $8b, $76, $69, $00, $30, $8b, $3c, $8b
	.byte $77, $2b, $8b, $37, $8b, $78, $27, $8b, $33, $8b, $79, $2b, $8b, $37, $8b, $78, $69, $01, $29, $8b, $35, $8b, $77, $33
	.byte $8b, $32, $8b, $76, $2e, $8b, $30, $8b, $75, $32, $8b, $33, $8b, $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $69, $02
	.byte $ff, $40
	.word @song1ref9
	.byte $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02
	.byte $ff, $40
	.word @song1ref9
	.byte $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02
	.byte $ff, $40
	.word @song1ref9
	.byte $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02
	.byte $ff, $40
	.word @song1ref9
	.byte $6b, $76, $69, $02
	.byte $ff, $38
	.word @song1ref9
	.byte $75, $33, $85, $00, $83, $76, $33, $85, $00, $83, $77, $65, .lobyte(@env18), .hibyte(@env18), $33, $85, $00, $83, $78
	.byte $67, $33, $85, $00, $83
@song1ch0loop:
	.byte $66, $6a, .lobyte(@tempo_env_4_3_mid), .hibyte(@tempo_env_4_3_mid)
	.byte $ff, $40
	.word @song1ref1
	.byte $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02
	.byte $ff, $40
	.word @song1ref9
	.byte $6b, $76, $69, $02
	.byte $ff, $38
	.word @song1ref9
	.byte $7b
@song1ref196:
	.byte $90, $2e, $99, $63, .lobyte(@env28), .hibyte(@env28), $95, $7a, $92, $2e, $83, $6b, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $30, $99, $79, $9b, $78, $9b, $77, $9b, $76, $9b, $75, $9b, $74, $9b, $7a, $30, $85, $74, $85, $7a, $32, $85, $74
	.byte $85, $7a, $33, $99, $79, $9b, $78, $9b, $7a, $35, $85, $74, $85, $7a, $33, $85, $74, $85, $79, $32, $99, $78, $9b, $77
	.byte $62, $61, $0a, $32, $28, $99, $76, $9b, $6b
	.byte $ff, $40
	.word @song1ref2
	.byte $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02
	.byte $ff, $40
	.word @song1ref9
	.byte $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02
	.byte $ff, $40
	.word @song1ref9
	.byte $6b, $76, $69, $02
	.byte $ff, $38
	.word @song1ref9
	.byte $75, $33, $85, $00, $83, $76, $33, $85, $00, $83, $77, $65, .lobyte(@env18), .hibyte(@env18), $33, $85, $00, $83, $78
	.byte $67, $33, $85, $00, $83, $6b, $79, $63, .lobyte(@env10), .hibyte(@env10), $64, $65, .lobyte(@env0), .hibyte(@env0)
	.byte $66
@song1ref334:
	.byte $94, $30, $a7, $69, $01, $84, $61, $33, $30, $2b, $85, $62, $2b, $9f, $69, $00, $94, $30, $99, $63, .lobyte(@env28)
	.byte .hibyte(@env28), $9b, $63, .lobyte(@env10), .hibyte(@env10), $64, $2b, $99, $30, $8b, $69, $00, $96, $61, $f0, $30
	.byte $32, $85, $62, $32, $83, $69, $01, $61, $f8, $32, $33, $85, $62, $33, $83, $69, $02, $61, $f2, $33, $35, $85, $62, $35
	.byte $83, $69, $01, $94, $33, $99, $63, .lobyte(@env28), .hibyte(@env28), $8d, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $69, $00, $32, $a7, $69, $01, $2e, $99, $78, $63, .lobyte(@env29), .hibyte(@env29), $8d, $77, $8d, $76, $8d, $75, $8d
	.byte $74, $8d, $73, $8d, $78, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $01, $96, $2b, $85, $00, $83, $2b, $85, $00
	.byte $83, $6b, $69, $00, $84, $30, $99, $63, .lobyte(@env27), .hibyte(@env27), $8d, $69, $00, $61, $33, $30, $2b, $85, $62
	.byte $2b, $9f, $69, $01, $94, $30, $99, $63, .lobyte(@env28), .hibyte(@env28), $9b, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $69, $00, $84, $33, $99, $69, $01, $32, $99, $69, $02, $30, $99, $69, $00, $61, $f5, $30, $35, $93, $62, $35, $83
	.byte $69, $01, $61, $10, $35, $30, $8b, $69, $00, $61, $13, $30, $2e, $85, $62, $2e, $bb, $63, .lobyte(@env29), .hibyte(@env29)
	.byte $d3, $62, $61, $1c, $2e, $26, $93, $62, $61, $0c, $26, $25, $83, $6b, $79, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $2e
	.word @song1ref334
	.byte $6b, $84, $33, $99, $63, .lobyte(@env27), .hibyte(@env27), $8d, $69, $01, $61, $17, $33, $2b, $93, $62, $2b, $91, $69
	.byte $02, $33, $af, $00, $83, $63, .lobyte(@env10), .hibyte(@env10), $64, $33, $99, $32, $99, $30, $99, $35, $8b, $61, $10
	.byte $35, $30, $8b, $30, $8b, $62, $37, $c3, $63, .lobyte(@env29), .hibyte(@env29), $b7, $62, $61, $1e, $37, $28, $99, $79
	.byte $63, .lobyte(@env10), .hibyte(@env10), $64, $94, $61, $16, $28, $26, $85, $74, $00, $83, $79, $22, $85, $74, $00, $83
	.byte $6b, $79, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $00, $84
@song1ref631:
	.byte $2e, $85, $61, $f2, $2e, $30, $83, $62, $30, $a7, $63, .lobyte(@env27), .hibyte(@env27), $9b, $62, $61, $1d, $30, $25
	.byte $99, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $01, $62, $32, $b5, $63, .lobyte(@env27), .hibyte(@env27), $9b
	.byte $62, $61, $1d, $32, $26, $99, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02, $33, $99, $69, $00, $61, $06, $33
	.byte $32, $85, $62, $32, $91, $69, $01, $61, $10, $32, $30, $85, $62, $30, $91, $69, $00, $61, $ea, $30, $37, $8b, $62, $37
	.byte $8b, $63, .lobyte(@env29), .hibyte(@env29), $b7, $63, .lobyte(@env10), .hibyte(@env10), $64, $61, $14, $37, $33, $85
	.byte $62, $33, $91, $62, $61, $1c, $33, $27, $99, $6b, $7a, $63, .lobyte(@env10), .hibyte(@env10), $64, $38, $85, $61, $f8
	.byte $38, $3a, $83, $62, $3a, $8b, $79, $9b, $78, $63, .lobyte(@env29), .hibyte(@env29), $9b, $77, $9b, $76, $9b, $75, $9b
	.byte $74, $9b, $73, $9b, $7a, $63, .lobyte(@env10), .hibyte(@env10), $64, $39, $99, $79, $9b, $78, $9b, $77, $9b, $76, $63
	.byte .lobyte(@env29), .hibyte(@env29), $9b, $75, $9b, $74, $9b, $73, $9b, $6b, $79, $63, .lobyte(@env10), .hibyte(@env10)
	.byte $64, $69, $00
	.byte $ff, $30
	.word @song1ref631
	.byte $7a, $63, .lobyte(@env10), .hibyte(@env10), $64, $3c, $99, $79, $9b, $78, $9b, $77, $9b, $76, $63, .lobyte(@env29)
	.byte .hibyte(@env29), $9b, $75, $9b, $7b, $63, .lobyte(@env10), .hibyte(@env10), $64
	.byte $ff, $20
	.word @song1ref196
	.byte $77, $62, $61, $02, $32, $28, $99, $76, $9b, $6b, $f7, $f7, $df, $73, $3e, $85, $00, $91, $74, $3e, $85, $00, $8b, $76
	.byte $85, $3e, $85, $00, $91, $78, $3e, $85, $00, $91, $6b
	.byte $ff, $40
	.word @song1ref1
	.byte $6b, $76, $63, .lobyte(@env10), .hibyte(@env10), $64, $69, $02
	.byte $ff, $40
	.word @song1ref9
	.byte $fd
	.word @song1ch0loop
@song1ch1:
@song1ref878:
	.byte $7a, $82, $0c, $a7, $69, $00, $0c, $a7, $0c, $a7, $0c, $99, $0c, $8b, $18, $99, $0a, $99, $0c, $a7, $0c, $a7, $0c, $a7
	.byte $0c, $99, $0c, $8b, $79, $69, $00, $84, $18, $85, $77, $85, $75, $87, $74, $85, $79, $69, $01, $0a, $85, $77, $85, $75
	.byte $87, $74, $85
	.byte $ff, $22
	.word @song1ref878
	.byte $ff, $22
	.word @song1ref878
	.byte $ff, $22
	.word @song1ref878
	.byte $ff, $22
	.word @song1ref878
	.byte $7a, $82, $0c, $a7, $0c, $a7, $0c, $a7, $0c, $99, $0c, $8b, $18, $99, $0a, $99, $0c, $a7, $0c, $a7, $0c, $a7, $0c, $99
	.byte $0c, $8b, $69, $02, $84, $18, $85, $79, $85, $78, $87, $74, $85, $7a, $69, $02, $18, $85, $79, $85, $77, $87, $74, $85
@song1ch1loop:
	.byte $66, $7a
@song1ref992:
	.byte $82, $0c, $a7, $0c, $a7, $0c, $a7, $0c, $99, $0c, $8b, $18, $99, $0a, $99, $0c, $a7, $0c, $a7, $0c, $a7, $0c, $99, $0c
	.byte $8b, $18, $99, $65, .lobyte(@env22), .hibyte(@env22), $69, $02, $80, $30, $99, $65, .lobyte(@env0), .hibyte(@env0)
	.byte $66, $82, $0c, $a7, $0c, $a7, $0c, $a7, $0c, $99, $0c, $8b, $18, $99, $0a, $99, $0c, $a7, $0c, $a7, $0c, $a7, $0c, $99
	.byte $0c, $8b, $18, $99, $65, .lobyte(@env5), .hibyte(@env5), $69, $02, $80, $2e, $99, $65, .lobyte(@env0), .hibyte(@env0)
	.byte $66
	.byte $ff, $36
	.word @song1ref992
	.byte $65, .lobyte(@env22), .hibyte(@env22), $69, $02, $80, $30, $99, $73, $63, .lobyte(@env27), .hibyte(@env27), $65, .lobyte(@env0)
	.byte .hibyte(@env0), $66, $69, $02, $84, $0c, $99, $74, $9b, $75, $9b, $76, $9b, $77, $9b, $78, $9b, $79, $9b, $7a, $9b
	.byte $9b, $79, $9b, $78, $9b, $77, $9b, $76, $9b, $75, $9b, $74, $9b, $73, $9b, $63, .lobyte(@env27), .hibyte(@env27), $69
	.byte $02, $0c, $99, $74, $9b, $75, $9b, $76, $9b, $77, $9b, $78, $9b, $79, $9b, $7a, $9b, $9b, $79, $9b, $78, $9b, $77, $9b
	.byte $76, $9b, $75, $9b, $74, $9b, $73, $9b, $63, .lobyte(@env27), .hibyte(@env27), $69, $02, $0e, $99, $74, $9b, $75, $9b
	.byte $76, $9b, $77, $9b, $78, $9b, $79, $9b, $7a, $9b, $9b, $79, $9b, $78, $9b, $77, $9b, $76, $9b, $75, $9b, $74, $9b, $73
	.byte $9b, $63, .lobyte(@env27), .hibyte(@env27), $69, $02, $0f, $99, $74, $9b, $75, $9b, $76, $9b, $77, $9b, $78, $9b, $79
	.byte $9b, $7a, $9b, $9b, $79, $9b, $78, $9b, $77, $9b, $76, $9b, $75, $9b, $74, $9b, $73, $9b
	.byte $ff, $22
	.word @song1ref878
@song1ref1234:
	.byte $7a, $82, $0f, $a7, $69, $00, $0f, $a7, $0f, $a7, $0f, $99, $0f, $8b, $1b, $99, $0e, $99, $0e, $a7, $0e, $a7, $0e, $a7
	.byte $0e, $99, $0e, $8b, $79, $69, $00, $84, $1a, $85, $77, $85, $75, $87, $74, $85, $79, $69, $01, $0c, $85, $77, $85, $75
	.byte $87, $74, $85
	.byte $ff, $22
	.word @song1ref878
	.byte $ff, $22
	.word @song1ref1234
	.byte $ff, $22
	.word @song1ref878
	.byte $ff, $22
	.word @song1ref1234
	.byte $ff, $22
	.word @song1ref878
	.byte $ff, $22
	.word @song1ref1234
	.byte $7a, $82, $0c, $a7, $0c, $a7, $0c, $a7, $0c, $99, $0c, $8b, $18, $99, $0a, $99, $0c, $a7, $0c, $a7, $0c, $a7, $0c, $99
	.byte $0c, $8b, $18, $99, $65, .lobyte(@env22), .hibyte(@env22), $69, $02, $80, $30, $99, $f7, $f7, $f7, $d7, $65, .lobyte(@env0)
	.byte .hibyte(@env0), $66
	.byte $ff, $38
	.word @song1ref992
	.byte $fd
	.word @song1ch1loop
@song1ch2:
@song1ref1353:
	.byte $98
@song1ref1354:
	.byte $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5
	.byte $2c, $b5, $2c, $b5, $2c, $b5, $2c, $8b, $2c, $8b, $2c, $8b, $2c, $8b
	.byte $ff, $26
	.word @song1ref1354
	.byte $ff, $26
	.word @song1ref1354
@song1ch2loop:
	.byte $ff, $1f
	.word @song1ref1353
	.byte $b5
	.byte $ff, $26
	.word @song1ref1354
	.byte $ff, $1f
	.word @song1ref1354
	.byte $b5
	.byte $ff, $26
	.word @song1ref1354
	.byte $ff, $1f
	.word @song1ref1354
	.byte $b5
	.byte $ff, $1f
	.word @song1ref1354
	.byte $b5
	.byte $ff, $1f
	.word @song1ref1354
	.byte $b5
	.byte $ff, $1f
	.word @song1ref1354
	.byte $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $b5, $2c, $8b, $2c, $8b, $2c, $8b, $2c, $8b, $f7
	.byte $f7, $f7, $9f, $2c, $8b, $2c, $8b, $2c, $8b, $2c, $8b
	.byte $ff, $1f
	.word @song1ref1354
	.byte $b5, $fd
	.word @song1ch2loop
@song1ch3:
	.byte $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $9b, $74, $86
@song1ref1481:
	.byte $24, $99, $00, $99, $25, $99, $00, $99, $27, $99, $00, $99, $29, $85, $00, $83, $29, $85, $00, $9f, $2b, $99, $00, $99
	.byte $29, $99, $00, $99, $26, $99, $00, $99, $2b, $85, $00, $83, $28, $85, $00, $83, $9b, $75, $23, $99, $00, $99, $24, $99
	.byte $00, $99, $27, $99, $00, $99, $26, $85, $00, $83, $23, $85, $00, $9f, $2b, $99, $00, $99, $29, $99, $00, $99, $26, $99
	.byte $00, $99, $2b, $85, $00, $83, $2c, $85, $00, $83, $9b, $74
	.byte $ff, $29
	.word @song1ref1481
	.byte $24, $99, $00, $99, $25, $99, $00, $99, $27, $99, $00, $99, $26, $85, $00, $83, $23, $85, $00, $9f, $2b, $99, $00, $99
	.byte $29, $99, $00, $99, $26, $99, $7a, $8a, $29, $8b, $29, $8b, $29, $8b, $29, $8b
@song1ch3loop:
@song1ref1609:
	.byte $73, $88
@song1ref1611:
	.byte $2c, $99, $72, $2b, $8b, $73, $2b, $8b, $7a, $8a, $29, $99, $74, $86, $26, $99, $73, $88, $2b, $8b, $72, $2b, $8b, $73
	.byte $2b, $8b, $72, $2b, $8b, $7a, $8a, $29, $99, $75, $86, $28, $99, $73, $88, $2c, $99, $72, $2b, $8b, $73, $2b, $8b, $7a
	.byte $8a, $29, $99, $74, $86, $2b, $99, $73, $88, $2b, $8b, $72, $2b, $8b, $73, $2b, $8b, $72, $2b, $8b, $7a, $8a, $29, $99
	.byte $73, $88, $2d, $8b, $2d, $8b
	.byte $ff, $2e
	.word @song1ref1611
	.byte $ff, $2e
	.word @song1ref1611
	.byte $ff, $29
	.word @song1ref1611
	.byte $8b, $29, $8b, $29, $8b, $29, $8b, $9b, $74, $88
@song1ref1708:
	.byte $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7, $74
	.byte $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $8b, $9b
	.byte $74
	.byte $ff, $21
	.word @song1ref1708
	.byte $74
	.byte $ff, $21
	.word @song1ref1708
	.byte $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7
	.byte $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $8b, $7a, $8a, $29, $8b, $29, $8b
	.byte $29, $8b, $29, $8b, $9b, $74, $88
@song1ref1819:
	.byte $2b, $8b, $72, $2b, $8b, $7a, $8a, $29, $99, $74, $88, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $8b, $7a, $8a
	.byte $29, $99, $74, $88, $2b, $8b, $72, $2b, $a7, $74, $2b, $8b, $72, $2b, $8b, $7a, $8a, $29, $99, $74, $88, $2b, $8b, $72
	.byte $2b, $a7, $74, $2b, $8b, $72, $2b, $8b, $7a, $8a, $29, $99, $74, $88, $2b, $8b, $72, $2b, $8b, $00, $99, $74
	.byte $ff, $28
	.word @song1ref1819
	.byte $9b, $74
	.byte $ff, $2a
	.word @song1ref1819
	.byte $74
	.byte $ff, $28
	.word @song1ref1819
	.byte $9b, $74
	.byte $ff, $2a
	.word @song1ref1819
	.byte $74
	.byte $ff, $2a
	.word @song1ref1819
	.byte $74
	.byte $ff, $2a
	.word @song1ref1819
	.byte $74
	.byte $ff, $2a
	.word @song1ref1819
	.byte $74
	.byte $ff, $28
	.word @song1ref1819
	.byte $73, $84, $61, $01, $20, $29, $ed, $74, $ef, $75, $ef, $77, $b7, $7a, $8a, $29, $8b, $29, $8b, $29, $8b, $29, $8b
	.byte $ff, $2e
	.word @song1ref1609
	.byte $ff, $2e
	.word @song1ref1611
	.byte $fd
	.word @song1ch3loop
@song1ch4:
	.byte $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7
@song1ch4loop:
@song1ref1979:
	.byte $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7
	.byte $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7
	.byte $ff, $20
	.word @song1ref1979
	.byte $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $f7, $f7, $f7, $d7, $fd
	.word @song1ch4loop
