.segment BANK(BK_END_CODE)

GAME_END_SCREEN_DATA:
	.incbin "resources/screen/game_end.nt"
	.incbin "resources/screen/game_end.nt_atr"

DIFF_LEVEL_WORDS:
	.BYTE "easy  ",$FF
	.BYTE "normal",$FF
	.BYTE "hard  ",$FF
DIFF_LEVEL_WORDS_OFFSET:
	.BYTE 0, 7, 14

WIN_MSG:
	.BYTE "you win. "
LOSE_MSG:
	.BYTE "you lose."

GAME_END_BG_PALETTE_DATA:
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
GAME_END_SPR_PALETTE_DATA:
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
