.segment "RAM"
SETTINGS_MENU: .RES 1

.segment BANK(BK_SETTINGS)

SETTINGS_BG_PALETTE_DATA:
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_BLUE | COLOR_LIGHTER
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_RED | COLOR_LIGHTER
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_GREEN | COLOR_LIGHTER
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE

SETTINGS_SPR_PALETTE_DATA:
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_BLACK,  COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE
	.BYTE	COLOR_BLACK, COLOR_GRAY_6, COLOR_GRAY_A, COLOR_WHITE

SETTINGS_SCREEN_DATA:
	.incbin "resources/screen/settings.nt"
	.incbin "resources/screen/settings.nt_atr"

SETTINGS_SPR_DATA:
	; PLAYER
	OAM_SPRITE_ENTRY  (11+0)*8, (20+0)*8, $80, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  (11+1)*8, (20+0)*8, $81, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  (11+2)*8, (20+0)*8, $82, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  (11+0)*8, (20+1)*8, $90, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  (11+1)*8, (20+1)*8, $91, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  (11+2)*8, (20+1)*8, $92, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  (11+0)*8, (20+2)*8, $A0, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  (11+1)*8, (20+2)*8, $A1, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  (11+2)*8, (20+2)*8, $A2, SPR_ATTR_PAL_0
	OAM_SPRITE_ENTRY  0,        255,      $4E, SPR_ATTR_PAL_1
